// Code generated by protoc-gen-go. DO NOT EDIT.
// source: as/integration/integration.proto

package integration

import (
	fmt "fmt"
	common "github.com/brocaar/chirpstack-api/go/v3/common"
	gw "github.com/brocaar/chirpstack-api/go/v3/gw"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorType int32

const (
	// Unknown type.
	ErrorType_UNKNOWN ErrorType = 0
	// Error related to the downlink payload size.
	// Usually seen when the payload exceeded the maximum allowed payload size.
	ErrorType_DOWNLINK_PAYLOAD_SIZE ErrorType = 1
	// Error related to the downlink frame-counter.
	// Usually seen when the frame-counter has already been used.
	ErrorType_DOWNLINK_FCNT ErrorType = 2
	// Uplink codec error.
	ErrorType_UPLINK_CODEC ErrorType = 3
	// Downlink codec error.
	ErrorType_DOWNLINK_CODEC ErrorType = 4
	// OTAA error.
	ErrorType_OTAA ErrorType = 5
	// Uplink frame-counter was reset.
	ErrorType_UPLINK_FCNT_RESET ErrorType = 6
	// Uplink MIC error.
	ErrorType_UPLINK_MIC ErrorType = 7
	// Uplink frame-counter retransmission.
	ErrorType_UPLINK_FCNT_RETRANSMISSION ErrorType = 8
	// Downlink gateway error.
	ErrorType_DOWNLINK_GATEWAY ErrorType = 9
)

var ErrorType_name = map[int32]string{
	0: "UNKNOWN",
	1: "DOWNLINK_PAYLOAD_SIZE",
	2: "DOWNLINK_FCNT",
	3: "UPLINK_CODEC",
	4: "DOWNLINK_CODEC",
	5: "OTAA",
	6: "UPLINK_FCNT_RESET",
	7: "UPLINK_MIC",
	8: "UPLINK_FCNT_RETRANSMISSION",
	9: "DOWNLINK_GATEWAY",
}

var ErrorType_value = map[string]int32{
	"UNKNOWN":                    0,
	"DOWNLINK_PAYLOAD_SIZE":      1,
	"DOWNLINK_FCNT":              2,
	"UPLINK_CODEC":               3,
	"DOWNLINK_CODEC":             4,
	"OTAA":                       5,
	"UPLINK_FCNT_RESET":          6,
	"UPLINK_MIC":                 7,
	"UPLINK_FCNT_RETRANSMISSION": 8,
	"DOWNLINK_GATEWAY":           9,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{0}
}

type LartechDeliveryStatus int32

const (
	LartechDeliveryStatus_ACCEPTED       LartechDeliveryStatus = 0
	LartechDeliveryStatus_REJECTED       LartechDeliveryStatus = 1
	LartechDeliveryStatus_ON_AIR         LartechDeliveryStatus = 2
	LartechDeliveryStatus_LOST           LartechDeliveryStatus = 3
	LartechDeliveryStatus_DELIVERED      LartechDeliveryStatus = 4
	LartechDeliveryStatus_ACCESS_DENIED  LartechDeliveryStatus = 5
	LartechDeliveryStatus_INTERNAL_ERROR LartechDeliveryStatus = 6
	LartechDeliveryStatus_CANCELLED      LartechDeliveryStatus = 7
)

var LartechDeliveryStatus_name = map[int32]string{
	0: "ACCEPTED",
	1: "REJECTED",
	2: "ON_AIR",
	3: "LOST",
	4: "DELIVERED",
	5: "ACCESS_DENIED",
	6: "INTERNAL_ERROR",
	7: "CANCELLED",
}

var LartechDeliveryStatus_value = map[string]int32{
	"ACCEPTED":       0,
	"REJECTED":       1,
	"ON_AIR":         2,
	"LOST":           3,
	"DELIVERED":      4,
	"ACCESS_DENIED":  5,
	"INTERNAL_ERROR": 6,
	"CANCELLED":      7,
}

func (x LartechDeliveryStatus) String() string {
	return proto.EnumName(LartechDeliveryStatus_name, int32(x))
}

func (LartechDeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{1}
}

// new format !
// UplinkEvent is the message sent when an uplink payload has been received.
type UplinkEvent struct {
	// Network-Server (frequency plan) ID.
	NsId uint32 `protobuf:"varint,1,opt,name=ns_id,json=nsID,proto3" json:"ns_id,omitempty"`
	// organization ID.
	OrganizationId uint32 `protobuf:"varint,2,opt,name=organization_id,json=orgID,proto3" json:"organization_id,omitempty"`
	// application ID.
	ApplicationId uint64 `protobuf:"varint,3,opt,name=application_id,json=appID,proto3" json:"application_id,omitempty"`
	// time when the message been published by the as. Service field. Used in logs!
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,6,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// TX info.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,7,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Device has ADR bit set.
	Adr bool `protobuf:"varint,8,opt,name=adr,proto3" json:"adr,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,9,opt,name=dr,proto3" json:"dr,omitempty"`
	// Frame counter.
	FCnt uint32 `protobuf:"varint,10,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame port.
	FPort uint32 `protobuf:"varint,11,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// FRMPayload data.
	Data []byte `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
	// JSON string containing the decoded object.
	// Note that this is only set when a codec is configured in the Device Profile.
	ObjectJson string `protobuf:"bytes,13,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// True if the uplink type is confirmed
	Confirmed bool `protobuf:"varint,15,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,16,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// mic for legacy. actility users. Modification
	Mic []byte `protobuf:"bytes,17,opt,name=mic,proto3" json:"mic,omitempty"`
	// true if packer late for more than 2min. Modification
	Late bool `protobuf:"varint,18,opt,name=late,proto3" json:"late,omitempty"`
	// time frame(s) recieved. Can be gps\fts\by server for packet with best SNR. Modification
	Time *timestamp.Timestamp `protobuf:"bytes,19,opt,name=time,proto3" json:"time,omitempty"`
	// Device Profile UUID as string
	DeviceProfileId string `protobuf:"bytes,20,opt,name=device_profile_id,json=dpID,proto3" json:"device_profile_id,omitempty"`
	// Service Profile UUID as string
	ServiceProfileId string `protobuf:"bytes,21,opt,name=service_profile_id,json=spID,proto3" json:"service_profile_id,omitempty"`
	// Routing Profile UUID as string
	RoutingProfileId int32 `protobuf:"varint,22,opt,name=routing_profile_id,json=rpID,proto3" json:"routing_profile_id,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications []uint64 `protobuf:"varint,23,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	// current class of the device: string: "A", "B", "C"
	Class string `protobuf:"bytes,24,opt,name=class,proto3" json:"class,omitempty"`
	// battery level last time recieved
	BatTime *timestamp.Timestamp `protobuf:"bytes,25,opt,name=bat_time,json=batTime,proto3" json:"bat_time,omitempty"`
	// battery level
	BatLevel float32 `protobuf:"fixed32,26,opt,name=bat_level,json=batLevel,proto3" json:"bat_level,omitempty"`
	// Receiving gateway RX info.
	RxInfo               []*gw.UplinkRXInfo `protobuf:"bytes,50,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UplinkEvent) Reset()         { *m = UplinkEvent{} }
func (m *UplinkEvent) String() string { return proto.CompactTextString(m) }
func (*UplinkEvent) ProtoMessage()    {}
func (*UplinkEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{0}
}

func (m *UplinkEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkEvent.Unmarshal(m, b)
}
func (m *UplinkEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkEvent.Marshal(b, m, deterministic)
}
func (m *UplinkEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkEvent.Merge(m, src)
}
func (m *UplinkEvent) XXX_Size() int {
	return xxx_messageInfo_UplinkEvent.Size(m)
}
func (m *UplinkEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkEvent proto.InternalMessageInfo

func (m *UplinkEvent) GetNsId() uint32 {
	if m != nil {
		return m.NsId
	}
	return 0
}

func (m *UplinkEvent) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *UplinkEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *UplinkEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *UplinkEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *UplinkEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *UplinkEvent) GetTxInfo() *gw.UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *UplinkEvent) GetAdr() bool {
	if m != nil {
		return m.Adr
	}
	return false
}

func (m *UplinkEvent) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *UplinkEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *UplinkEvent) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *UplinkEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UplinkEvent) GetObjectJson() string {
	if m != nil {
		return m.ObjectJson
	}
	return ""
}

func (m *UplinkEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UplinkEvent) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *UplinkEvent) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *UplinkEvent) GetMic() []byte {
	if m != nil {
		return m.Mic
	}
	return nil
}

func (m *UplinkEvent) GetLate() bool {
	if m != nil {
		return m.Late
	}
	return false
}

func (m *UplinkEvent) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *UplinkEvent) GetDeviceProfileId() string {
	if m != nil {
		return m.DeviceProfileId
	}
	return ""
}

func (m *UplinkEvent) GetServiceProfileId() string {
	if m != nil {
		return m.ServiceProfileId
	}
	return ""
}

func (m *UplinkEvent) GetRoutingProfileId() int32 {
	if m != nil {
		return m.RoutingProfileId
	}
	return 0
}

func (m *UplinkEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

func (m *UplinkEvent) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *UplinkEvent) GetBatTime() *timestamp.Timestamp {
	if m != nil {
		return m.BatTime
	}
	return nil
}

func (m *UplinkEvent) GetBatLevel() float32 {
	if m != nil {
		return m.BatLevel
	}
	return 0
}

func (m *UplinkEvent) GetRxInfo() []*gw.UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

// JoinEvent is the message sent when a device joined the network.
// Note that this is only sent after the first received uplink after the
// device (re)activation.
type JoinEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,5,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Receiving gateway RX info.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,6,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// TX info.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,7,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,8,opt,name=dr,proto3" json:"dr,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications         []uint64 `protobuf:"varint,11,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinEvent) Reset()         { *m = JoinEvent{} }
func (m *JoinEvent) String() string { return proto.CompactTextString(m) }
func (*JoinEvent) ProtoMessage()    {}
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{1}
}

func (m *JoinEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinEvent.Unmarshal(m, b)
}
func (m *JoinEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinEvent.Marshal(b, m, deterministic)
}
func (m *JoinEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinEvent.Merge(m, src)
}
func (m *JoinEvent) XXX_Size() int {
	return xxx_messageInfo_JoinEvent.Size(m)
}
func (m *JoinEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinEvent.DiscardUnknown(m)
}

var xxx_messageInfo_JoinEvent proto.InternalMessageInfo

func (m *JoinEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *JoinEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *JoinEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *JoinEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *JoinEvent) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *JoinEvent) GetRxInfo() []*gw.UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

func (m *JoinEvent) GetTxInfo() *gw.UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *JoinEvent) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *JoinEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *JoinEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *JoinEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

// AckEvent is the message sent when a confirmation on a confirmed downlink
// has been received -or- when the downlink timed out.
type AckEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Frame was acknowledged.
	Acknowledged bool `protobuf:"varint,5,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Downlink frame counter to which the acknowledgement relates.
	FCnt uint32 `protobuf:"varint,6,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// optional. the id was generated on client's side to control tx
	MessageId string `protobuf:"bytes,9,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications         []uint64 `protobuf:"varint,10,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckEvent) Reset()         { *m = AckEvent{} }
func (m *AckEvent) String() string { return proto.CompactTextString(m) }
func (*AckEvent) ProtoMessage()    {}
func (*AckEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{2}
}

func (m *AckEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckEvent.Unmarshal(m, b)
}
func (m *AckEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckEvent.Marshal(b, m, deterministic)
}
func (m *AckEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckEvent.Merge(m, src)
}
func (m *AckEvent) XXX_Size() int {
	return xxx_messageInfo_AckEvent.Size(m)
}
func (m *AckEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AckEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AckEvent proto.InternalMessageInfo

func (m *AckEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *AckEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *AckEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *AckEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *AckEvent) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

func (m *AckEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *AckEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AckEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *AckEvent) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *AckEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

// TxAckEvent is the message sent when a downlink was acknowledged by the gateway
// for transmission. As a downlink can be scheduled in the future, this event
// does not confirm that the message has already been transmitted.
type TxAckEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Downlink frame-counter.
	FCnt uint32 `protobuf:"varint,5,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,7,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// TX info.
	TxInfo *gw.DownlinkTXInfo `protobuf:"bytes,8,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// optional. the id was generated on client's side to control tx
	MessageId string `protobuf:"bytes,10,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications         []uint64 `protobuf:"varint,11,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxAckEvent) Reset()         { *m = TxAckEvent{} }
func (m *TxAckEvent) String() string { return proto.CompactTextString(m) }
func (*TxAckEvent) ProtoMessage()    {}
func (*TxAckEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{3}
}

func (m *TxAckEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxAckEvent.Unmarshal(m, b)
}
func (m *TxAckEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxAckEvent.Marshal(b, m, deterministic)
}
func (m *TxAckEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxAckEvent.Merge(m, src)
}
func (m *TxAckEvent) XXX_Size() int {
	return xxx_messageInfo_TxAckEvent.Size(m)
}
func (m *TxAckEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TxAckEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TxAckEvent proto.InternalMessageInfo

func (m *TxAckEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *TxAckEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *TxAckEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *TxAckEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *TxAckEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *TxAckEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TxAckEvent) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *TxAckEvent) GetTxInfo() *gw.DownlinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *TxAckEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *TxAckEvent) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *TxAckEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

// ErrorEvent is the message sent when an error occurred.
type ErrorEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Error type.
	Type ErrorType `protobuf:"varint,5,opt,name=type,proto3,enum=integration.ErrorType" json:"type,omitempty"`
	// Error message.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Downlink frame-counter (in case the downlink is related to a scheduled downlink).
	FCnt uint32 `protobuf:"varint,7,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications []uint64 `protobuf:"varint,10,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	// id of DL message. In case the error is about downlink message
	MessageId            string   `protobuf:"bytes,11,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorEvent) Reset()         { *m = ErrorEvent{} }
func (m *ErrorEvent) String() string { return proto.CompactTextString(m) }
func (*ErrorEvent) ProtoMessage()    {}
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{4}
}

func (m *ErrorEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorEvent.Unmarshal(m, b)
}
func (m *ErrorEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorEvent.Marshal(b, m, deterministic)
}
func (m *ErrorEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorEvent.Merge(m, src)
}
func (m *ErrorEvent) XXX_Size() int {
	return xxx_messageInfo_ErrorEvent.Size(m)
}
func (m *ErrorEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorEvent proto.InternalMessageInfo

func (m *ErrorEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *ErrorEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ErrorEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *ErrorEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *ErrorEvent) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_UNKNOWN
}

func (m *ErrorEvent) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ErrorEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *ErrorEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ErrorEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *ErrorEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

func (m *ErrorEvent) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

// StatusEvent is the message sent when a device-status mac-command was sent
// by the device.
type StatusEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// The demodulation signal-to-noise ratio in dB for the last successfully
	// received device-status request by the Network Server.
	Margin int32 `protobuf:"varint,5,opt,name=margin,proto3" json:"margin,omitempty"`
	// Device is connected to an external power source.
	ExternalPowerSource bool `protobuf:"varint,6,opt,name=external_power_source,json=externalPowerSource,proto3" json:"external_power_source,omitempty"`
	// Battery level is not available.
	BatteryLevelUnavailable bool `protobuf:"varint,7,opt,name=battery_level_unavailable,json=batteryLevelUnavailable,proto3" json:"battery_level_unavailable,omitempty"`
	// Battery level.
	BatteryLevel float32 `protobuf:"fixed32,8,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications         []uint64 `protobuf:"varint,11,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusEvent) Reset()         { *m = StatusEvent{} }
func (m *StatusEvent) String() string { return proto.CompactTextString(m) }
func (*StatusEvent) ProtoMessage()    {}
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{5}
}

func (m *StatusEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusEvent.Unmarshal(m, b)
}
func (m *StatusEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusEvent.Marshal(b, m, deterministic)
}
func (m *StatusEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusEvent.Merge(m, src)
}
func (m *StatusEvent) XXX_Size() int {
	return xxx_messageInfo_StatusEvent.Size(m)
}
func (m *StatusEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StatusEvent proto.InternalMessageInfo

func (m *StatusEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *StatusEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *StatusEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *StatusEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *StatusEvent) GetMargin() int32 {
	if m != nil {
		return m.Margin
	}
	return 0
}

func (m *StatusEvent) GetExternalPowerSource() bool {
	if m != nil {
		return m.ExternalPowerSource
	}
	return false
}

func (m *StatusEvent) GetBatteryLevelUnavailable() bool {
	if m != nil {
		return m.BatteryLevelUnavailable
	}
	return false
}

func (m *StatusEvent) GetBatteryLevel() float32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *StatusEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StatusEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *StatusEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

// LocationEvent is the message sent when a geolocation resolve was returned.
type LocationEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Location.
	Location *common.Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Uplink IDs used for geolocation.
	// This is set in case the geolocation is based on the uplink meta-data.
	UplinkIds [][]byte `protobuf:"bytes,7,rep,name=uplink_ids,json=uplinkIDs,proto3" json:"uplink_ids,omitempty"`
	// Frame counter (in case the geolocation is based on the payload).
	// This is set in case the geolocation is based on the uplink payload content.
	FCnt uint32 `protobuf:"varint,8,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications         []uint64 `protobuf:"varint,10,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationEvent) Reset()         { *m = LocationEvent{} }
func (m *LocationEvent) String() string { return proto.CompactTextString(m) }
func (*LocationEvent) ProtoMessage()    {}
func (*LocationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{6}
}

func (m *LocationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationEvent.Unmarshal(m, b)
}
func (m *LocationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationEvent.Marshal(b, m, deterministic)
}
func (m *LocationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationEvent.Merge(m, src)
}
func (m *LocationEvent) XXX_Size() int {
	return xxx_messageInfo_LocationEvent.Size(m)
}
func (m *LocationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LocationEvent proto.InternalMessageInfo

func (m *LocationEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *LocationEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *LocationEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *LocationEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *LocationEvent) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LocationEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *LocationEvent) GetUplinkIds() [][]byte {
	if m != nil {
		return m.UplinkIds
	}
	return nil
}

func (m *LocationEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *LocationEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *LocationEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

// IntegrationEvent is the message that can be sent by an integration.
// It allows for sending events which are provided by an external integration
// which are "not native" to ChirpStack.
type IntegrationEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Integration name.
	IntegrationName string `protobuf:"bytes,6,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	// Event type.
	EventType string `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// JSON string containing the event object.
	ObjectJson string `protobuf:"bytes,8,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Application ID list. The param is using by global integrations only
	Applications         []uint64 `protobuf:"varint,10,rep,packed,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntegrationEvent) Reset()         { *m = IntegrationEvent{} }
func (m *IntegrationEvent) String() string { return proto.CompactTextString(m) }
func (*IntegrationEvent) ProtoMessage()    {}
func (*IntegrationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{7}
}

func (m *IntegrationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationEvent.Unmarshal(m, b)
}
func (m *IntegrationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationEvent.Marshal(b, m, deterministic)
}
func (m *IntegrationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationEvent.Merge(m, src)
}
func (m *IntegrationEvent) XXX_Size() int {
	return xxx_messageInfo_IntegrationEvent.Size(m)
}
func (m *IntegrationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationEvent proto.InternalMessageInfo

func (m *IntegrationEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *IntegrationEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *IntegrationEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *IntegrationEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *IntegrationEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *IntegrationEvent) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

func (m *IntegrationEvent) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *IntegrationEvent) GetObjectJson() string {
	if m != nil {
		return m.ObjectJson
	}
	return ""
}

func (m *IntegrationEvent) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *IntegrationEvent) GetApplications() []uint64 {
	if m != nil {
		return m.Applications
	}
	return nil
}

// Lartech Co LTD Custom format for passing data to Ernet.uplink topic
// UplinkEvent is the message sent when an uplink payload has been received.
type LartechUplinkEvent struct {
	MessageId    string `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	DevEui       string `protobuf:"bytes,2,opt,name=devEui,proto3" json:"devEui,omitempty"`
	GatewayEui   string `protobuf:"bytes,3,opt,name=gatewayEui,proto3" json:"gatewayEui,omitempty"`
	AppId        string `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`
	RxTime       int64  `protobuf:"varint,5,opt,name=rxTime,proto3" json:"rxTime,omitempty"`
	FrameCounter int32  `protobuf:"varint,6,opt,name=frameCounter,proto3" json:"frameCounter,omitempty"`
	Confirmed    bool   `protobuf:"varint,7,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Frequency    int32  `protobuf:"varint,8,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Types that are valid to be assigned to Modulation:
	//	*LartechUplinkEvent_LoraModulation
	//	*LartechUplinkEvent_FskModulation
	Modulation           isLartechUplinkEvent_Modulation `protobuf_oneof:"modulation"`
	Snr                  float32                         `protobuf:"fixed32,11,opt,name=snr,proto3" json:"snr,omitempty"`
	Rssi                 float32                         `protobuf:"fixed32,12,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Fport                *wrappers.Int32Value            `protobuf:"bytes,13,opt,name=fport,proto3" json:"fport,omitempty"`
	FrmPayload           []byte                          `protobuf:"bytes,14,opt,name=frmPayload,proto3" json:"frmPayload,omitempty"`
	Owner                *wrappers.StringValue           `protobuf:"bytes,15,opt,name=owner,proto3" json:"owner,omitempty"`
	Stat                 *wrappers.Int32Value            `protobuf:"bytes,16,opt,name=stat,proto3" json:"stat,omitempty"`
	RfChain              *wrappers.Int32Value            `protobuf:"bytes,17,opt,name=rfChain,proto3" json:"rfChain,omitempty"`
	Size                 *wrappers.Int32Value            `protobuf:"bytes,18,opt,name=size,proto3" json:"size,omitempty"`
	Firmware             *wrappers.StringValue           `protobuf:"bytes,19,opt,name=firmware,proto3" json:"firmware,omitempty"`
	FirstMessage         *wrappers.BoolValue             `protobuf:"bytes,20,opt,name=firstMessage,proto3" json:"firstMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *LartechUplinkEvent) Reset()         { *m = LartechUplinkEvent{} }
func (m *LartechUplinkEvent) String() string { return proto.CompactTextString(m) }
func (*LartechUplinkEvent) ProtoMessage()    {}
func (*LartechUplinkEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{8}
}

func (m *LartechUplinkEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LartechUplinkEvent.Unmarshal(m, b)
}
func (m *LartechUplinkEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LartechUplinkEvent.Marshal(b, m, deterministic)
}
func (m *LartechUplinkEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LartechUplinkEvent.Merge(m, src)
}
func (m *LartechUplinkEvent) XXX_Size() int {
	return xxx_messageInfo_LartechUplinkEvent.Size(m)
}
func (m *LartechUplinkEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LartechUplinkEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LartechUplinkEvent proto.InternalMessageInfo

func (m *LartechUplinkEvent) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *LartechUplinkEvent) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *LartechUplinkEvent) GetGatewayEui() string {
	if m != nil {
		return m.GatewayEui
	}
	return ""
}

func (m *LartechUplinkEvent) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LartechUplinkEvent) GetRxTime() int64 {
	if m != nil {
		return m.RxTime
	}
	return 0
}

func (m *LartechUplinkEvent) GetFrameCounter() int32 {
	if m != nil {
		return m.FrameCounter
	}
	return 0
}

func (m *LartechUplinkEvent) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *LartechUplinkEvent) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type isLartechUplinkEvent_Modulation interface {
	isLartechUplinkEvent_Modulation()
}

type LartechUplinkEvent_LoraModulation struct {
	LoraModulation *LoRaModulation `protobuf:"bytes,9,opt,name=loraModulation,proto3,oneof"`
}

type LartechUplinkEvent_FskModulation struct {
	FskModulation *FSKModulation `protobuf:"bytes,10,opt,name=fskModulation,proto3,oneof"`
}

func (*LartechUplinkEvent_LoraModulation) isLartechUplinkEvent_Modulation() {}

func (*LartechUplinkEvent_FskModulation) isLartechUplinkEvent_Modulation() {}

func (m *LartechUplinkEvent) GetModulation() isLartechUplinkEvent_Modulation {
	if m != nil {
		return m.Modulation
	}
	return nil
}

func (m *LartechUplinkEvent) GetLoraModulation() *LoRaModulation {
	if x, ok := m.GetModulation().(*LartechUplinkEvent_LoraModulation); ok {
		return x.LoraModulation
	}
	return nil
}

func (m *LartechUplinkEvent) GetFskModulation() *FSKModulation {
	if x, ok := m.GetModulation().(*LartechUplinkEvent_FskModulation); ok {
		return x.FskModulation
	}
	return nil
}

func (m *LartechUplinkEvent) GetSnr() float32 {
	if m != nil {
		return m.Snr
	}
	return 0
}

func (m *LartechUplinkEvent) GetRssi() float32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *LartechUplinkEvent) GetFport() *wrappers.Int32Value {
	if m != nil {
		return m.Fport
	}
	return nil
}

func (m *LartechUplinkEvent) GetFrmPayload() []byte {
	if m != nil {
		return m.FrmPayload
	}
	return nil
}

func (m *LartechUplinkEvent) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *LartechUplinkEvent) GetStat() *wrappers.Int32Value {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *LartechUplinkEvent) GetRfChain() *wrappers.Int32Value {
	if m != nil {
		return m.RfChain
	}
	return nil
}

func (m *LartechUplinkEvent) GetSize() *wrappers.Int32Value {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *LartechUplinkEvent) GetFirmware() *wrappers.StringValue {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func (m *LartechUplinkEvent) GetFirstMessage() *wrappers.BoolValue {
	if m != nil {
		return m.FirstMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LartechUplinkEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LartechUplinkEvent_LoraModulation)(nil),
		(*LartechUplinkEvent_FskModulation)(nil),
	}
}

// the soother is for  LartechUplinkEvent
type LoRaModulation struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoRaModulation) Reset()         { *m = LoRaModulation{} }
func (m *LoRaModulation) String() string { return proto.CompactTextString(m) }
func (*LoRaModulation) ProtoMessage()    {}
func (*LoRaModulation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{9}
}

func (m *LoRaModulation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoRaModulation.Unmarshal(m, b)
}
func (m *LoRaModulation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoRaModulation.Marshal(b, m, deterministic)
}
func (m *LoRaModulation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoRaModulation.Merge(m, src)
}
func (m *LoRaModulation) XXX_Size() int {
	return xxx_messageInfo_LoRaModulation.Size(m)
}
func (m *LoRaModulation) XXX_DiscardUnknown() {
	xxx_messageInfo_LoRaModulation.DiscardUnknown(m)
}

var xxx_messageInfo_LoRaModulation proto.InternalMessageInfo

func (m *LoRaModulation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// the soother is for LartechUplinkEvent
type FSKModulation struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FSKModulation) Reset()         { *m = FSKModulation{} }
func (m *FSKModulation) String() string { return proto.CompactTextString(m) }
func (*FSKModulation) ProtoMessage()    {}
func (*FSKModulation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{10}
}

func (m *FSKModulation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSKModulation.Unmarshal(m, b)
}
func (m *FSKModulation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSKModulation.Marshal(b, m, deterministic)
}
func (m *FSKModulation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSKModulation.Merge(m, src)
}
func (m *FSKModulation) XXX_Size() int {
	return xxx_messageInfo_FSKModulation.Size(m)
}
func (m *FSKModulation) XXX_DiscardUnknown() {
	xxx_messageInfo_FSKModulation.DiscardUnknown(m)
}

var xxx_messageInfo_FSKModulation proto.InternalMessageInfo

func (m *FSKModulation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// the soother is for LartechDownlink
type StatusRepliesMode struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRepliesMode) Reset()         { *m = StatusRepliesMode{} }
func (m *StatusRepliesMode) String() string { return proto.CompactTextString(m) }
func (*StatusRepliesMode) ProtoMessage()    {}
func (*StatusRepliesMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{11}
}

func (m *StatusRepliesMode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRepliesMode.Unmarshal(m, b)
}
func (m *StatusRepliesMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRepliesMode.Marshal(b, m, deterministic)
}
func (m *StatusRepliesMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRepliesMode.Merge(m, src)
}
func (m *StatusRepliesMode) XXX_Size() int {
	return xxx_messageInfo_StatusRepliesMode.Size(m)
}
func (m *StatusRepliesMode) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRepliesMode.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRepliesMode proto.InternalMessageInfo

func (m *StatusRepliesMode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// the soother is for LartechDownlink
type DownlinkType struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownlinkType) Reset()         { *m = DownlinkType{} }
func (m *DownlinkType) String() string { return proto.CompactTextString(m) }
func (*DownlinkType) ProtoMessage()    {}
func (*DownlinkType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{12}
}

func (m *DownlinkType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownlinkType.Unmarshal(m, b)
}
func (m *DownlinkType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownlinkType.Marshal(b, m, deterministic)
}
func (m *DownlinkType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownlinkType.Merge(m, src)
}
func (m *DownlinkType) XXX_Size() int {
	return xxx_messageInfo_DownlinkType.Size(m)
}
func (m *DownlinkType) XXX_DiscardUnknown() {
	xxx_messageInfo_DownlinkType.DiscardUnknown(m)
}

var xxx_messageInfo_DownlinkType proto.InternalMessageInfo

func (m *DownlinkType) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// the soother is for LartechDownlink. Orig backbone.types.RxWindow
type RxWindow struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RxWindow) Reset()         { *m = RxWindow{} }
func (m *RxWindow) String() string { return proto.CompactTextString(m) }
func (*RxWindow) ProtoMessage()    {}
func (*RxWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{13}
}

func (m *RxWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RxWindow.Unmarshal(m, b)
}
func (m *RxWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RxWindow.Marshal(b, m, deterministic)
}
func (m *RxWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RxWindow.Merge(m, src)
}
func (m *RxWindow) XXX_Size() int {
	return xxx_messageInfo_RxWindow.Size(m)
}
func (m *RxWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_RxWindow.DiscardUnknown(m)
}

var xxx_messageInfo_RxWindow proto.InternalMessageInfo

func (m *RxWindow) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// messages from Lartech Kafka
type LartechDownlink struct {
	MessageId            string                `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	DevEui               string                `protobuf:"bytes,2,opt,name=devEui,proto3" json:"devEui,omitempty"`
	AppId                string                `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	Retries              *wrappers.Int32Value  `protobuf:"bytes,4,opt,name=retries,proto3" json:"retries,omitempty"`
	Fport                *wrappers.Int32Value  `protobuf:"bytes,5,opt,name=fport,proto3" json:"fport,omitempty"`
	FrmPayloads          [][]byte              `protobuf:"bytes,6,rep,name=frmPayloads,proto3" json:"frmPayloads,omitempty"`
	EnableStatusReplies  bool                  `protobuf:"varint,7,opt,name=enableStatusReplies,proto3" json:"enableStatusReplies,omitempty"`
	RxWindowHint         *RxWindow             `protobuf:"bytes,8,opt,name=rxWindowHint,proto3" json:"rxWindowHint,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	StatusRepliesModes   []*StatusRepliesMode  `protobuf:"bytes,10,rep,name=statusRepliesModes,proto3" json:"statusRepliesModes,omitempty"`
	AlreadySentChunks    *wrappers.Int32Value  `protobuf:"bytes,11,opt,name=alreadySentChunks,proto3" json:"alreadySentChunks,omitempty"`
	DownlinkType         *DownlinkType         `protobuf:"bytes,12,opt,name=downlinkType,proto3" json:"downlinkType,omitempty"`
	TimeZoneHours        *wrappers.Int32Value  `protobuf:"bytes,13,opt,name=timeZoneHours,proto3" json:"timeZoneHours,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LartechDownlink) Reset()         { *m = LartechDownlink{} }
func (m *LartechDownlink) String() string { return proto.CompactTextString(m) }
func (*LartechDownlink) ProtoMessage()    {}
func (*LartechDownlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{14}
}

func (m *LartechDownlink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LartechDownlink.Unmarshal(m, b)
}
func (m *LartechDownlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LartechDownlink.Marshal(b, m, deterministic)
}
func (m *LartechDownlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LartechDownlink.Merge(m, src)
}
func (m *LartechDownlink) XXX_Size() int {
	return xxx_messageInfo_LartechDownlink.Size(m)
}
func (m *LartechDownlink) XXX_DiscardUnknown() {
	xxx_messageInfo_LartechDownlink.DiscardUnknown(m)
}

var xxx_messageInfo_LartechDownlink proto.InternalMessageInfo

func (m *LartechDownlink) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *LartechDownlink) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *LartechDownlink) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LartechDownlink) GetRetries() *wrappers.Int32Value {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *LartechDownlink) GetFport() *wrappers.Int32Value {
	if m != nil {
		return m.Fport
	}
	return nil
}

func (m *LartechDownlink) GetFrmPayloads() [][]byte {
	if m != nil {
		return m.FrmPayloads
	}
	return nil
}

func (m *LartechDownlink) GetEnableStatusReplies() bool {
	if m != nil {
		return m.EnableStatusReplies
	}
	return false
}

func (m *LartechDownlink) GetRxWindowHint() *RxWindow {
	if m != nil {
		return m.RxWindowHint
	}
	return nil
}

func (m *LartechDownlink) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *LartechDownlink) GetStatusRepliesModes() []*StatusRepliesMode {
	if m != nil {
		return m.StatusRepliesModes
	}
	return nil
}

func (m *LartechDownlink) GetAlreadySentChunks() *wrappers.Int32Value {
	if m != nil {
		return m.AlreadySentChunks
	}
	return nil
}

func (m *LartechDownlink) GetDownlinkType() *DownlinkType {
	if m != nil {
		return m.DownlinkType
	}
	return nil
}

func (m *LartechDownlink) GetTimeZoneHours() *wrappers.Int32Value {
	if m != nil {
		return m.TimeZoneHours
	}
	return nil
}

type LartechDownlinkMessageStatus struct {
	MessageId            string                `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	DevEui               string                `protobuf:"bytes,2,opt,name=devEui,proto3" json:"devEui,omitempty"`
	Status               LartechDeliveryStatus `protobuf:"varint,3,opt,name=status,proto3,enum=integration.LartechDeliveryStatus" json:"status,omitempty"`
	StatusDescription    *wrappers.StringValue `protobuf:"bytes,4,opt,name=statusDescription,proto3" json:"statusDescription,omitempty"`
	AppId                string                `protobuf:"bytes,5,opt,name=appId,proto3" json:"appId,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	SentChunks           int32                 `protobuf:"varint,7,opt,name=sentChunks,proto3" json:"sentChunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LartechDownlinkMessageStatus) Reset()         { *m = LartechDownlinkMessageStatus{} }
func (m *LartechDownlinkMessageStatus) String() string { return proto.CompactTextString(m) }
func (*LartechDownlinkMessageStatus) ProtoMessage()    {}
func (*LartechDownlinkMessageStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{15}
}

func (m *LartechDownlinkMessageStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LartechDownlinkMessageStatus.Unmarshal(m, b)
}
func (m *LartechDownlinkMessageStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LartechDownlinkMessageStatus.Marshal(b, m, deterministic)
}
func (m *LartechDownlinkMessageStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LartechDownlinkMessageStatus.Merge(m, src)
}
func (m *LartechDownlinkMessageStatus) XXX_Size() int {
	return xxx_messageInfo_LartechDownlinkMessageStatus.Size(m)
}
func (m *LartechDownlinkMessageStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LartechDownlinkMessageStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LartechDownlinkMessageStatus proto.InternalMessageInfo

func (m *LartechDownlinkMessageStatus) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *LartechDownlinkMessageStatus) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *LartechDownlinkMessageStatus) GetStatus() LartechDeliveryStatus {
	if m != nil {
		return m.Status
	}
	return LartechDeliveryStatus_ACCEPTED
}

func (m *LartechDownlinkMessageStatus) GetStatusDescription() *wrappers.StringValue {
	if m != nil {
		return m.StatusDescription
	}
	return nil
}

func (m *LartechDownlinkMessageStatus) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LartechDownlinkMessageStatus) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *LartechDownlinkMessageStatus) GetSentChunks() int32 {
	if m != nil {
		return m.SentChunks
	}
	return 0
}

// UplinkDefault is the message sent when an uplink payload has been received.
type UplinkDefault struct {
	// Network-Server (frequency plan) ID.
	NsId uint32 `protobuf:"varint,1,opt,name=ns_id,json=nsID,proto3" json:"ns_id,omitempty"`
	// organization ID.
	OrganizationId uint32 `protobuf:"varint,2,opt,name=organization_id,json=orgID,proto3" json:"organization_id,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI. HEX-string
	DevEui string `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device has ADR bit set.
	Adr bool `protobuf:"varint,5,opt,name=adr,proto3" json:"adr,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,6,opt,name=dr,proto3" json:"dr,omitempty"`
	// Frame counter.
	FCnt uint32 `protobuf:"varint,7,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame port.
	FPort uint32 `protobuf:"varint,8,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// FRMPayload data. HEX-string
	Data string `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// True if the uplink type is confirmed
	Confirmed bool `protobuf:"varint,11,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	// Device address.
	DevAddr string `protobuf:"bytes,12,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// mic for legacy. actility users. Modification
	Mic string `protobuf:"bytes,13,opt,name=mic,proto3" json:"mic,omitempty"`
	// true if packer late for more than 2min. Modification
	Late bool `protobuf:"varint,14,opt,name=late,proto3" json:"late,omitempty"`
	// time when the frame(s) had been recieved. Can be gps\fts\by server for packet with best SNR.
	Time *timestamp.Timestamp `protobuf:"bytes,15,opt,name=time,proto3" json:"time,omitempty"`
	// Device Profile UUID as string
	DeviceProfileId string `protobuf:"bytes,16,opt,name=device_profile_id,json=dpID,proto3" json:"device_profile_id,omitempty"`
	// Service Profile UUID as string
	ServiceProfileId string `protobuf:"bytes,17,opt,name=service_profile_id,json=spID,proto3" json:"service_profile_id,omitempty"`
	// current class of the device: string: "A", "B", "C"
	Class string `protobuf:"bytes,18,opt,name=class,proto3" json:"class,omitempty"`
	// battery level last time recieved
	BatTime *timestamp.Timestamp `protobuf:"bytes,19,opt,name=bat_time,json=batTime,proto3" json:"bat_time,omitempty"`
	// battery level
	BatLevel float32 `protobuf:"fixed32,20,opt,name=bat_level,json=batLevel,proto3" json:"bat_level,omitempty"`
	// true if the device works not from the battery but from external power
	// (when bat_level value is 255)
	ExtPower bool `protobuf:"varint,21,opt,name=ext_power,json=extPower,proto3" json:"ext_power,omitempty"`
	// true - means battery level is unavailible. When bat_level value is 0)
	NoBatLvl bool `protobuf:"varint,22,opt,name=no_bat_lvl,json=noBatLvl,proto3" json:"no_bat_lvl,omitempty"`
	// JSON string containing the decoded object.
	// Note that this is only set when a codec is configured in the Device Profile.
	ObjectJson string `protobuf:"bytes,23,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// Receiving gateway RX info.
	RxInfo               []*UplinkRXInfoDefault `protobuf:"bytes,50,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UplinkDefault) Reset()         { *m = UplinkDefault{} }
func (m *UplinkDefault) String() string { return proto.CompactTextString(m) }
func (*UplinkDefault) ProtoMessage()    {}
func (*UplinkDefault) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{16}
}

func (m *UplinkDefault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkDefault.Unmarshal(m, b)
}
func (m *UplinkDefault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkDefault.Marshal(b, m, deterministic)
}
func (m *UplinkDefault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkDefault.Merge(m, src)
}
func (m *UplinkDefault) XXX_Size() int {
	return xxx_messageInfo_UplinkDefault.Size(m)
}
func (m *UplinkDefault) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkDefault.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkDefault proto.InternalMessageInfo

func (m *UplinkDefault) GetNsId() uint32 {
	if m != nil {
		return m.NsId
	}
	return 0
}

func (m *UplinkDefault) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *UplinkDefault) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *UplinkDefault) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *UplinkDefault) GetAdr() bool {
	if m != nil {
		return m.Adr
	}
	return false
}

func (m *UplinkDefault) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *UplinkDefault) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *UplinkDefault) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *UplinkDefault) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *UplinkDefault) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UplinkDefault) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *UplinkDefault) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *UplinkDefault) GetMic() string {
	if m != nil {
		return m.Mic
	}
	return ""
}

func (m *UplinkDefault) GetLate() bool {
	if m != nil {
		return m.Late
	}
	return false
}

func (m *UplinkDefault) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *UplinkDefault) GetDeviceProfileId() string {
	if m != nil {
		return m.DeviceProfileId
	}
	return ""
}

func (m *UplinkDefault) GetServiceProfileId() string {
	if m != nil {
		return m.ServiceProfileId
	}
	return ""
}

func (m *UplinkDefault) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *UplinkDefault) GetBatTime() *timestamp.Timestamp {
	if m != nil {
		return m.BatTime
	}
	return nil
}

func (m *UplinkDefault) GetBatLevel() float32 {
	if m != nil {
		return m.BatLevel
	}
	return 0
}

func (m *UplinkDefault) GetExtPower() bool {
	if m != nil {
		return m.ExtPower
	}
	return false
}

func (m *UplinkDefault) GetNoBatLvl() bool {
	if m != nil {
		return m.NoBatLvl
	}
	return false
}

func (m *UplinkDefault) GetObjectJson() string {
	if m != nil {
		return m.ObjectJson
	}
	return ""
}

func (m *UplinkDefault) GetRxInfo() []*UplinkRXInfoDefault {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type UplinkRXInfoDefault struct {
	// Gateway ID.
	GatewayId string `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// RSSI.
	Rssi int32 `protobuf:"varint,2,opt,name=rssi,proto3" json:"rssi,omitempty"`
	// LoRa SNR.
	LoraSnr float64 `protobuf:"fixed64,3,opt,name=lora_snr,json=loRaSNR,proto3" json:"lora_snr,omitempty"`
	// Channel.
	Channel uint32 `protobuf:"varint,4,opt,name=channel,proto3" json:"channel,omitempty"`
	// Location.
	Location *common.Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// Fine-timestamp type.
	FineTimestampType gw.FineTimestampType `protobuf:"varint,6,opt,name=fine_timestamp_type,json=fineTimestampType,proto3,enum=gw.FineTimestampType" json:"fine_timestamp_type,omitempty"`
	// Fine-timestamp data.
	//
	// Types that are valid to be assigned to FineTimestamp:
	//	*UplinkRXInfoDefault_EncryptedFineTimestamp
	//	*UplinkRXInfoDefault_PlainFineTimestamp
	FineTimestamp isUplinkRXInfoDefault_FineTimestamp `protobuf_oneof:"fine_timestamp"`
	// Gateway specific context.
	Context string `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	// Uplink ID (UUID bytes).
	// Unique and random ID which can be used to correlate the uplink across multiple logs.
	UplinkId             string   `protobuf:"bytes,10,opt,name=uplink_id,json=uplinkID,proto3" json:"uplink_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UplinkRXInfoDefault) Reset()         { *m = UplinkRXInfoDefault{} }
func (m *UplinkRXInfoDefault) String() string { return proto.CompactTextString(m) }
func (*UplinkRXInfoDefault) ProtoMessage()    {}
func (*UplinkRXInfoDefault) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{17}
}

func (m *UplinkRXInfoDefault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkRXInfoDefault.Unmarshal(m, b)
}
func (m *UplinkRXInfoDefault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkRXInfoDefault.Marshal(b, m, deterministic)
}
func (m *UplinkRXInfoDefault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkRXInfoDefault.Merge(m, src)
}
func (m *UplinkRXInfoDefault) XXX_Size() int {
	return xxx_messageInfo_UplinkRXInfoDefault.Size(m)
}
func (m *UplinkRXInfoDefault) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkRXInfoDefault.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkRXInfoDefault proto.InternalMessageInfo

func (m *UplinkRXInfoDefault) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *UplinkRXInfoDefault) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *UplinkRXInfoDefault) GetLoraSnr() float64 {
	if m != nil {
		return m.LoraSnr
	}
	return 0
}

func (m *UplinkRXInfoDefault) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *UplinkRXInfoDefault) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *UplinkRXInfoDefault) GetFineTimestampType() gw.FineTimestampType {
	if m != nil {
		return m.FineTimestampType
	}
	return gw.FineTimestampType_NONE
}

type isUplinkRXInfoDefault_FineTimestamp interface {
	isUplinkRXInfoDefault_FineTimestamp()
}

type UplinkRXInfoDefault_EncryptedFineTimestamp struct {
	EncryptedFineTimestamp *gw.EncryptedFineTimestamp `protobuf:"bytes,7,opt,name=encrypted_fine_timestamp,json=encryptedFineTimestamp,proto3,oneof"`
}

type UplinkRXInfoDefault_PlainFineTimestamp struct {
	PlainFineTimestamp *gw.PlainFineTimestamp `protobuf:"bytes,8,opt,name=plain_fine_timestamp,json=plainFineTimestamp,proto3,oneof"`
}

func (*UplinkRXInfoDefault_EncryptedFineTimestamp) isUplinkRXInfoDefault_FineTimestamp() {}

func (*UplinkRXInfoDefault_PlainFineTimestamp) isUplinkRXInfoDefault_FineTimestamp() {}

func (m *UplinkRXInfoDefault) GetFineTimestamp() isUplinkRXInfoDefault_FineTimestamp {
	if m != nil {
		return m.FineTimestamp
	}
	return nil
}

func (m *UplinkRXInfoDefault) GetEncryptedFineTimestamp() *gw.EncryptedFineTimestamp {
	if x, ok := m.GetFineTimestamp().(*UplinkRXInfoDefault_EncryptedFineTimestamp); ok {
		return x.EncryptedFineTimestamp
	}
	return nil
}

func (m *UplinkRXInfoDefault) GetPlainFineTimestamp() *gw.PlainFineTimestamp {
	if x, ok := m.GetFineTimestamp().(*UplinkRXInfoDefault_PlainFineTimestamp); ok {
		return x.PlainFineTimestamp
	}
	return nil
}

func (m *UplinkRXInfoDefault) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *UplinkRXInfoDefault) GetUplinkId() string {
	if m != nil {
		return m.UplinkId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UplinkRXInfoDefault) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UplinkRXInfoDefault_EncryptedFineTimestamp)(nil),
		(*UplinkRXInfoDefault_PlainFineTimestamp)(nil),
	}
}

func init() {
	proto.RegisterEnum("integration.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterEnum("integration.LartechDeliveryStatus", LartechDeliveryStatus_name, LartechDeliveryStatus_value)
	proto.RegisterType((*UplinkEvent)(nil), "integration.UplinkEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.UplinkEvent.TagsEntry")
	proto.RegisterType((*JoinEvent)(nil), "integration.JoinEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.JoinEvent.TagsEntry")
	proto.RegisterType((*AckEvent)(nil), "integration.AckEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.AckEvent.TagsEntry")
	proto.RegisterType((*TxAckEvent)(nil), "integration.TxAckEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.TxAckEvent.TagsEntry")
	proto.RegisterType((*ErrorEvent)(nil), "integration.ErrorEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.ErrorEvent.TagsEntry")
	proto.RegisterType((*StatusEvent)(nil), "integration.StatusEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.StatusEvent.TagsEntry")
	proto.RegisterType((*LocationEvent)(nil), "integration.LocationEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.LocationEvent.TagsEntry")
	proto.RegisterType((*IntegrationEvent)(nil), "integration.IntegrationEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.IntegrationEvent.TagsEntry")
	proto.RegisterType((*LartechUplinkEvent)(nil), "integration.LartechUplinkEvent")
	proto.RegisterType((*LoRaModulation)(nil), "integration.LoRaModulation")
	proto.RegisterType((*FSKModulation)(nil), "integration.FSKModulation")
	proto.RegisterType((*StatusRepliesMode)(nil), "integration.StatusRepliesMode")
	proto.RegisterType((*DownlinkType)(nil), "integration.DownlinkType")
	proto.RegisterType((*RxWindow)(nil), "integration.RxWindow")
	proto.RegisterType((*LartechDownlink)(nil), "integration.LartechDownlink")
	proto.RegisterType((*LartechDownlinkMessageStatus)(nil), "integration.LartechDownlinkMessageStatus")
	proto.RegisterType((*UplinkDefault)(nil), "integration.UplinkDefault")
	proto.RegisterMapType((map[string]string)(nil), "integration.UplinkDefault.TagsEntry")
	proto.RegisterType((*UplinkRXInfoDefault)(nil), "integration.UplinkRXInfoDefault")
}

func init() {
	proto.RegisterFile("as/integration/integration.proto", fileDescriptor_5ba82681be587591)
}

var fileDescriptor_5ba82681be587591 = []byte{
	// 2448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x5a, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x36, 0xff, 0x81, 0x43, 0x52, 0x86, 0x56, 0x96, 0x4d, 0x2b, 0xb2, 0xcc, 0x2a, 0xed, 0x54,
	0x49, 0x5b, 0xaa, 0x95, 0x9b, 0x34, 0x49, 0xa7, 0x9d, 0xa1, 0x48, 0xa4, 0xa6, 0x23, 0x53, 0x9a,
	0x25, 0x1d, 0x37, 0xb9, 0xe1, 0xac, 0x88, 0x25, 0x85, 0x08, 0x04, 0xd0, 0xc5, 0x52, 0x94, 0xfc,
	0x10, 0x7d, 0x80, 0x3e, 0x40, 0xfa, 0x18, 0xbd, 0xeb, 0x7d, 0x27, 0x0f, 0xd0, 0x69, 0x2f, 0xdb,
	0x97, 0xe8, 0xec, 0x2e, 0x08, 0x02, 0x20, 0x6b, 0xd9, 0x72, 0x3a, 0xa3, 0x5e, 0x89, 0x7b, 0xf6,
	0xec, 0xc1, 0x9e, 0xfd, 0xce, 0x77, 0xf6, 0xe7, 0x08, 0xea, 0x24, 0xd8, 0xb7, 0x5d, 0x4e, 0xc7,
	0x8c, 0x70, 0xdb, 0x73, 0xe3, 0xbf, 0x1b, 0x3e, 0xf3, 0xb8, 0x87, 0xca, 0x31, 0xd1, 0xd6, 0xc6,
	0xd0, 0x9b, 0x4c, 0x3c, 0x77, 0x5f, 0xfd, 0x51, 0x1a, 0x5b, 0x8f, 0xc7, 0x9e, 0x37, 0x76, 0xe8,
	0xbe, 0x6c, 0x9d, 0x4e, 0x47, 0xfb, 0xdc, 0x9e, 0xd0, 0x80, 0x93, 0x89, 0x1f, 0x2a, 0x94, 0xc7,
	0xb3, 0xfd, 0xf1, 0x2c, 0x6c, 0xec, 0xa4, 0xb5, 0x67, 0x8c, 0xf8, 0x3e, 0x65, 0x81, 0xea, 0xdf,
	0xfd, 0xb6, 0x04, 0xe5, 0x17, 0xbe, 0x63, 0xbb, 0xe7, 0xe6, 0x05, 0x75, 0x39, 0xda, 0x80, 0x82,
	0x1b, 0x0c, 0x6c, 0xab, 0x96, 0xa9, 0x67, 0xf6, 0xaa, 0x38, 0xef, 0x06, 0x9d, 0x36, 0xda, 0x81,
	0xbb, 0x1e, 0x1b, 0x13, 0xd7, 0x7e, 0x25, 0xe7, 0x25, 0xba, 0xb3, 0xb2, 0xbb, 0xe0, 0xb1, 0x71,
	0xa7, 0x8d, 0x1e, 0xc1, 0x1a, 0xf1, 0x7d, 0xc7, 0x1e, 0x46, 0xdd, 0xb9, 0x7a, 0x66, 0x2f, 0x8f,
	0x0b, 0xc4, 0xf7, 0x3b, 0x6d, 0xf4, 0x1b, 0xa8, 0xf8, 0xd3, 0x53, 0xc7, 0x0e, 0xce, 0xa8, 0x35,
	0x20, 0xbc, 0x96, 0xaf, 0x67, 0xf6, 0xca, 0x07, 0x5b, 0x0d, 0x35, 0xb5, 0xc6, 0x7c, 0x6a, 0x8d,
	0xfe, 0xdc, 0x11, 0x5c, 0x8e, 0xf4, 0x9b, 0x1c, 0x3d, 0x86, 0xb2, 0x45, 0x2f, 0xec, 0x21, 0x1d,
	0xb8, 0x64, 0x42, 0x6b, 0x85, 0x7a, 0x66, 0x4f, 0xc7, 0xa0, 0x44, 0x5d, 0x32, 0xa1, 0xe8, 0x01,
	0x94, 0x2c, 0x7a, 0x31, 0xa0, 0x53, 0xbb, 0x56, 0xac, 0x67, 0xf6, 0x2a, 0xb8, 0x68, 0xd1, 0x0b,
	0xf3, 0x45, 0x07, 0x7d, 0x00, 0x25, 0x7e, 0x39, 0xb0, 0xdd, 0x91, 0x57, 0x2b, 0xc9, 0x6f, 0x1a,
	0x8d, 0xf1, 0xac, 0xa1, 0xdc, 0xed, 0xff, 0xbe, 0xe3, 0x8e, 0x3c, 0x5c, 0xe4, 0x97, 0xe2, 0x2f,
	0x32, 0x20, 0x47, 0x2c, 0x56, 0xd3, 0xea, 0x99, 0x3d, 0x0d, 0x8b, 0x9f, 0x68, 0x0d, 0xb2, 0x16,
	0xab, 0xe9, 0xd2, 0xcf, 0xac, 0xc5, 0xc4, 0xca, 0x8c, 0x06, 0x43, 0x97, 0xd7, 0x40, 0xad, 0xcc,
	0xa8, 0xe5, 0x72, 0xb4, 0x09, 0xc5, 0xd1, 0xc0, 0xf7, 0x18, 0xaf, 0x95, 0xd5, 0x82, 0x8c, 0x4e,
	0x3c, 0xc6, 0x11, 0x82, 0xbc, 0x45, 0x38, 0xa9, 0x55, 0xe4, 0x74, 0xe4, 0x6f, 0xe1, 0x86, 0x77,
	0xfa, 0x0d, 0x1d, 0xf2, 0xc1, 0x37, 0x81, 0xe7, 0xd6, 0xaa, 0xca, 0x0d, 0x25, 0x7a, 0xd6, 0x3b,
	0xee, 0xa2, 0x8f, 0x21, 0xcf, 0xc9, 0x38, 0xa8, 0xad, 0xd5, 0x73, 0x7b, 0xe5, 0x83, 0xdd, 0x46,
	0x3c, 0x38, 0x62, 0x10, 0x35, 0xfa, 0x64, 0x1c, 0x98, 0x2e, 0x67, 0x57, 0x58, 0xea, 0xa3, 0x6d,
	0xd0, 0x87, 0x9e, 0x3b, 0xb2, 0xd9, 0x84, 0x5a, 0xb5, 0xbb, 0xd2, 0x81, 0x85, 0x00, 0x3d, 0x04,
	0x4d, 0x2c, 0x0e, 0xb1, 0x2c, 0x56, 0x33, 0xe4, 0x74, 0xc4, 0x62, 0x35, 0x2d, 0x8b, 0x09, 0x9f,
	0x27, 0xf6, 0xb0, 0xb6, 0x2e, 0xa5, 0xe2, 0xa7, 0x98, 0xb7, 0x43, 0x38, 0xad, 0x21, 0x69, 0x45,
	0xfe, 0x46, 0x0d, 0xc8, 0x8b, 0x08, 0xab, 0x6d, 0x5c, 0x8b, 0x9a, 0xd4, 0x43, 0x8f, 0x61, 0x3d,
	0x84, 0xcb, 0x67, 0xde, 0xc8, 0x76, 0xa8, 0x88, 0x87, 0x7b, 0xd2, 0xdb, 0xbc, 0x25, 0xc2, 0xa1,
	0x0e, 0x28, 0xa0, 0x2c, 0xad, 0xb1, 0xa9, 0x34, 0x82, 0x50, 0x83, 0x79, 0x53, 0x6e, 0xbb, 0xe3,
	0xb8, 0xc6, 0xfd, 0x7a, 0x66, 0xaf, 0x80, 0xf3, 0x4c, 0x68, 0xec, 0x42, 0x25, 0x16, 0x71, 0x41,
	0xed, 0x41, 0x3d, 0xb7, 0x97, 0xc7, 0x09, 0x19, 0xba, 0x07, 0x85, 0xa1, 0x43, 0x82, 0xa0, 0x56,
	0x93, 0xa6, 0x55, 0x03, 0x7d, 0x04, 0xda, 0x29, 0xe1, 0x03, 0xe9, 0xd2, 0xc3, 0x6b, 0x5d, 0x2a,
	0x9d, 0x12, 0x2e, 0x5a, 0xe8, 0x3d, 0xd0, 0xc5, 0x30, 0x87, 0x5e, 0x50, 0xa7, 0xb6, 0x55, 0xcf,
	0xec, 0x65, 0xb1, 0xb0, 0x73, 0x24, 0xda, 0x22, 0xce, 0x58, 0x18, 0x67, 0x07, 0x12, 0xbc, 0x58,
	0x9c, 0xe1, 0x30, 0xce, 0x98, 0x8c, 0xb3, 0xad, 0x5f, 0x81, 0x1e, 0xe1, 0x27, 0x00, 0x38, 0xa7,
	0x57, 0x92, 0x6a, 0x3a, 0x16, 0x3f, 0xc5, 0x9c, 0x2f, 0x88, 0x33, 0xa5, 0x92, 0x5f, 0x3a, 0x56,
	0x8d, 0xcf, 0xb2, 0x9f, 0x64, 0x76, 0xff, 0x95, 0x03, 0xfd, 0x99, 0x67, 0xbb, 0x8a, 0xa6, 0x3f,
	0x5a, 0x62, 0x5c, 0x46, 0x32, 0xae, 0x1a, 0x93, 0x76, 0xda, 0xe8, 0x03, 0x30, 0xe2, 0x6a, 0x92,
	0x3f, 0xca, 0xf2, 0xdd, 0x98, 0x5c, 0x92, 0x28, 0xc5, 0xb2, 0xdc, 0xeb, 0x58, 0x96, 0x4f, 0xb0,
	0x2c, 0x1e, 0x61, 0x85, 0x64, 0x84, 0xc5, 0x16, 0xa6, 0xf8, 0xfa, 0x85, 0x79, 0x1b, 0xae, 0x2a,
	0x66, 0x6a, 0x11, 0x33, 0x7f, 0x19, 0x12, 0x47, 0x97, 0x9f, 0xa8, 0x27, 0x88, 0x13, 0x2d, 0xd9,
	0x12, 0x6d, 0xd2, 0x59, 0x09, 0xde, 0x2e, 0x2b, 0xa5, 0x23, 0xb0, 0xbc, 0x1c, 0x81, 0x37, 0x07,
	0xfb, 0x2f, 0x39, 0xd0, 0x9a, 0xc3, 0xf3, 0xdb, 0x87, 0xb5, 0xf0, 0x7a, 0x78, 0xee, 0x7a, 0x33,
	0x87, 0x5a, 0x63, 0x6a, 0x49, 0xbc, 0x35, 0x9c, 0x90, 0x2d, 0x12, 0x65, 0x31, 0x96, 0x28, 0x9f,
	0x84, 0x18, 0x95, 0x24, 0x46, 0x8f, 0x13, 0x18, 0xcd, 0x3d, 0xbd, 0x16, 0x22, 0xed, 0xed, 0x20,
	0x7a, 0x04, 0x30, 0xa1, 0x41, 0x40, 0xc6, 0x32, 0x7d, 0xe8, 0xd2, 0x4b, 0x3d, 0x94, 0x74, 0xac,
	0x25, 0x04, 0xe1, 0xfb, 0x44, 0xf0, 0xdf, 0x39, 0x80, 0xfe, 0xe5, 0xad, 0xc4, 0x30, 0xc2, 0xa7,
	0x10, 0xc3, 0xe7, 0xa3, 0x10, 0x1f, 0x45, 0xd3, 0x1f, 0x24, 0xf0, 0x59, 0xf8, 0xb1, 0x84, 0xd0,
	0x23, 0x80, 0x31, 0xe1, 0x74, 0x46, 0xae, 0x84, 0x4f, 0x25, 0xf9, 0x1d, 0x3d, 0x94, 0x74, 0xda,
	0xe8, 0x27, 0x0b, 0x52, 0x2b, 0xec, 0x90, 0x20, 0x75, 0xdb, 0x9b, 0xb9, 0x2b, 0x68, 0x9d, 0x46,
	0x5b, 0x7f, 0x17, 0xb4, 0xe1, 0x3a, 0xb4, 0xbf, 0x57, 0xbe, 0xfe, 0x23, 0x07, 0x60, 0x32, 0xe6,
	0xb1, 0xdb, 0x87, 0xf6, 0x87, 0x90, 0xe7, 0x57, 0xbe, 0x3a, 0x36, 0xad, 0x1d, 0xdc, 0x4f, 0x00,
	0x2b, 0xa7, 0xdc, 0xbf, 0xf2, 0x29, 0x96, 0x3a, 0xc2, 0x41, 0x2a, 0x44, 0x92, 0xb9, 0x3a, 0x56,
	0x8d, 0x45, 0xbc, 0x94, 0x56, 0xc4, 0x8b, 0xb6, 0x22, 0x5e, 0x16, 0x2b, 0x71, 0x2d, 0xa3, 0xf5,
	0x77, 0x4b, 0xba, 0x2b, 0x28, 0x9b, 0x8a, 0x83, 0x72, 0x2a, 0x0e, 0x6e, 0x8e, 0xf1, 0x9f, 0xf2,
	0x50, 0xee, 0x71, 0xc2, 0xa7, 0xc1, 0xed, 0x03, 0xf9, 0x3e, 0x14, 0x27, 0x84, 0x8d, 0x6d, 0x57,
	0xc2, 0x5c, 0xc0, 0x61, 0x0b, 0x1d, 0xc0, 0x26, 0xbd, 0xe4, 0x94, 0xb9, 0xc4, 0x19, 0xf8, 0xde,
	0x8c, 0xb2, 0x41, 0xe0, 0x4d, 0xd9, 0x90, 0x4a, 0x80, 0x35, 0xbc, 0x31, 0xef, 0x3c, 0x11, 0x7d,
	0x3d, 0xd9, 0x85, 0x3e, 0x83, 0x87, 0xa7, 0x84, 0x73, 0xca, 0xae, 0xd4, 0x69, 0x67, 0x30, 0x75,
	0xc9, 0x05, 0xb1, 0x1d, 0x72, 0xea, 0x50, 0x19, 0x02, 0x1a, 0x7e, 0x10, 0x2a, 0xc8, 0xd3, 0xcf,
	0x8b, 0x45, 0x37, 0x7a, 0x1f, 0xaa, 0x89, 0xb1, 0x92, 0xf5, 0x59, 0x5c, 0x89, 0xeb, 0x47, 0xe7,
	0x5c, 0x7d, 0xc5, 0x39, 0x37, 0xb6, 0xc0, 0xff, 0x57, 0x1b, 0xf6, 0x77, 0x39, 0xa8, 0x1e, 0x79,
	0xca, 0xcc, 0xed, 0x0b, 0x8f, 0x9f, 0x82, 0xe6, 0x84, 0x93, 0x93, 0x01, 0x22, 0x0e, 0x57, 0xe1,
	0x9d, 0x72, 0x3e, 0x69, 0x1c, 0x69, 0xa0, 0x4f, 0x12, 0x5b, 0xc1, 0x0f, 0x13, 0xf8, 0x24, 0x7c,
	0x5c, 0xb5, 0x1b, 0x4c, 0xe5, 0x81, 0x6d, 0x60, 0x5b, 0x6a, 0xab, 0xaf, 0x60, 0x5d, 0x49, 0x3a,
	0xed, 0x60, 0x91, 0x48, 0xb4, 0x58, 0x22, 0xf9, 0xdf, 0x67, 0x84, 0x9b, 0xa3, 0xfa, 0xcf, 0x1c,
	0x18, 0x9d, 0x85, 0xf7, 0xb7, 0x0f, 0xd8, 0x5f, 0x87, 0x50, 0x15, 0x24, 0x54, 0x3f, 0x4e, 0x40,
	0x95, 0x9e, 0xf8, 0x12, 0x5a, 0x1f, 0x80, 0x11, 0xd3, 0x57, 0xdf, 0x56, 0x89, 0xff, 0x6e, 0x4c,
	0x2e, 0x27, 0xf0, 0x08, 0x80, 0x0a, 0x1b, 0x03, 0xb9, 0x95, 0x94, 0x54, 0x4e, 0x95, 0x12, 0xb1,
	0x7b, 0xa4, 0xaf, 0xb6, 0xda, 0xd2, 0xd5, 0xf6, 0x36, 0x83, 0xfc, 0xb7, 0x22, 0xa0, 0x23, 0xc2,
	0x38, 0x1d, 0x9e, 0xc5, 0x1f, 0x42, 0xb6, 0x61, 0xb1, 0x69, 0x84, 0x86, 0x62, 0xa7, 0x89, 0xfb,
	0x20, 0x21, 0x98, 0xda, 0xa1, 0xbd, 0xb0, 0x85, 0x76, 0xa2, 0xf3, 0x90, 0xe8, 0x0b, 0x91, 0x5c,
	0x48, 0xc4, 0x34, 0x88, 0xef, 0x77, 0x2c, 0x89, 0xa3, 0xae, 0x1e, 0x48, 0xa4, 0x35, 0x76, 0x29,
	0x7c, 0x97, 0xec, 0xcc, 0xe1, 0xb0, 0x25, 0xfc, 0x1e, 0x31, 0x32, 0xa1, 0x2d, 0x6f, 0xea, 0x72,
	0xaa, 0xb6, 0xe5, 0x02, 0x4e, 0xc8, 0x92, 0xb7, 0xff, 0x52, 0xfa, 0xf6, 0xbf, 0x0d, 0xfa, 0x88,
	0xd1, 0x3f, 0x4c, 0xa9, 0x3b, 0xbc, 0x92, 0xb8, 0x14, 0xf0, 0x42, 0x80, 0x4c, 0x58, 0x73, 0x3c,
	0x46, 0x9e, 0x7b, 0xd6, 0xd4, 0x51, 0xd9, 0x41, 0x01, 0xf3, 0x5e, 0x8a, 0xf3, 0x38, 0xa6, 0xf2,
	0xf4, 0x0e, 0x4e, 0x0d, 0x42, 0x87, 0x50, 0x1d, 0x05, 0xe7, 0x31, 0x2b, 0xf3, 0xcc, 0x1c, 0xb7,
	0xf2, 0x79, 0xef, 0x8b, 0x84, 0x91, 0xe4, 0x10, 0x81, 0x58, 0xe0, 0x32, 0xb9, 0x5d, 0x67, 0xb1,
	0xf8, 0x89, 0x10, 0xe4, 0x59, 0x10, 0xd8, 0xf2, 0x0d, 0x25, 0x8b, 0xe5, 0x6f, 0xf4, 0x0b, 0x28,
	0x8c, 0xe4, 0x6b, 0x4b, 0x35, 0x9c, 0x67, 0x3a, 0x80, 0x3a, 0x2e, 0x7f, 0x72, 0xf0, 0xa5, 0xc0,
	0x16, 0x2b, 0x4d, 0x81, 0xc8, 0x88, 0x4d, 0x4e, 0xc8, 0x95, 0xe3, 0x11, 0xab, 0xb6, 0x26, 0xe9,
	0x13, 0x93, 0xa0, 0x03, 0x28, 0x78, 0x33, 0x97, 0x32, 0xf9, 0x72, 0x52, 0x3e, 0xd8, 0x5e, 0x32,
	0xd9, 0xe3, 0xcc, 0x76, 0xc7, 0xa1, 0x4d, 0xa9, 0x8a, 0xf6, 0x21, 0x1f, 0x70, 0xc2, 0xe5, 0x7b,
	0xca, 0x35, 0xb3, 0x90, 0x8a, 0xe8, 0x23, 0x28, 0xb1, 0x51, 0xeb, 0x8c, 0xd8, 0xae, 0x7c, 0x6d,
	0xb9, 0x66, 0xcc, 0x5c, 0x57, 0x7e, 0xc7, 0x7e, 0xa5, 0x9e, 0x63, 0xae, 0xfd, 0x8e, 0xfd, 0x8a,
	0xa2, 0x4f, 0x40, 0x13, 0xc0, 0xcf, 0x08, 0x9b, 0xbf, 0xd7, 0xbc, 0xde, 0x9f, 0x48, 0x1b, 0xfd,
	0x16, 0x2a, 0x23, 0x9b, 0x05, 0xfc, 0xb9, 0x0a, 0x71, 0xf9, 0x60, 0xb3, 0x8a, 0xa1, 0x87, 0x9e,
	0xe7, 0xa8, 0xb1, 0x09, 0xfd, 0xc3, 0x0a, 0xc0, 0x24, 0x42, 0x73, 0xb7, 0x0e, 0x6b, 0xc9, 0xa8,
	0x11, 0x77, 0xf6, 0x30, 0x53, 0x16, 0x70, 0xd6, 0xb6, 0x76, 0x1f, 0x43, 0x35, 0x11, 0x11, 0x4b,
	0x0a, 0xef, 0xc3, 0xba, 0x3a, 0x0c, 0x60, 0xea, 0x3b, 0x36, 0x0d, 0x9e, 0x7b, 0x16, 0x5d, 0x52,
	0xda, 0x81, 0x4a, 0x74, 0x99, 0x10, 0x89, 0x28, 0xdd, 0xbf, 0x05, 0x1a, 0xbe, 0x7c, 0x69, 0xbb,
	0x96, 0x37, 0x5b, 0xea, 0xfb, 0x73, 0x01, 0xee, 0x86, 0xbc, 0x9f, 0xdb, 0xb8, 0x21, 0xe9, 0x23,
	0x52, 0xe7, 0xe2, 0xa4, 0x16, 0x98, 0x53, 0xce, 0x6c, 0x1a, 0x84, 0x0f, 0x9e, 0xd7, 0x60, 0xae,
	0x74, 0x17, 0x21, 0x5e, 0x78, 0xe3, 0x10, 0xaf, 0x43, 0x79, 0x11, 0xd0, 0x6a, 0xdf, 0xae, 0xe0,
	0xb8, 0x08, 0xfd, 0x1c, 0x36, 0xa8, 0x2b, 0x4e, 0x68, 0x89, 0x25, 0x0d, 0xd3, 0xc5, 0xaa, 0x2e,
	0xf4, 0x29, 0x54, 0x58, 0xb8, 0x72, 0x4f, 0x6d, 0x77, 0x7e, 0xf5, 0xde, 0x4c, 0x50, 0x7a, 0xbe,
	0xb4, 0x38, 0xa1, 0xba, 0x60, 0x94, 0xfe, 0xe6, 0x8c, 0xea, 0x02, 0x0a, 0xd2, 0x68, 0xab, 0x3c,
	0x5f, 0x3e, 0xd8, 0x59, 0x71, 0x42, 0x8c, 0xa9, 0xe1, 0x15, 0x23, 0x51, 0x07, 0xd6, 0x89, 0xc3,
	0x28, 0xb1, 0xae, 0x7a, 0xd4, 0xe5, 0xad, 0xb3, 0xa9, 0x7b, 0x1e, 0xc8, 0xe4, 0x72, 0xcd, 0x8a,
	0x2e, 0x8f, 0x12, 0x7b, 0x97, 0x15, 0x8b, 0x31, 0x99, 0x8f, 0xca, 0x07, 0x0f, 0x13, 0x93, 0x8a,
	0x07, 0x21, 0x4e, 0xa8, 0xa3, 0x26, 0x54, 0xb9, 0x3d, 0xa1, 0x5f, 0x7b, 0x2e, 0x7d, 0xea, 0x4d,
	0x59, 0xf0, 0x26, 0xa9, 0x2b, 0x39, 0x62, 0xf7, 0xaf, 0x59, 0xd8, 0x4e, 0x45, 0x6a, 0x48, 0x3b,
	0xb5, 0x18, 0x37, 0x0c, 0xdb, 0xcf, 0xa0, 0xa8, 0x56, 0x4e, 0xc6, 0xed, 0x5a, 0xea, 0x24, 0x3e,
	0xff, 0x20, 0x75, 0xec, 0x0b, 0xca, 0xae, 0xc2, 0x65, 0x0f, 0x47, 0xa0, 0x67, 0xb0, 0xae, 0x7e,
	0xb5, 0x69, 0x30, 0x64, 0xb6, 0x2f, 0xd3, 0x7e, 0xfe, 0x0d, 0xf0, 0x5e, 0x1e, 0xb6, 0xa0, 0x4f,
	0x21, 0x4e, 0x9f, 0x28, 0x8a, 0x8a, 0x6f, 0x1e, 0x45, 0x3b, 0x00, 0xc1, 0x02, 0xee, 0x92, 0xa4,
	0x7a, 0x4c, 0xb2, 0xfb, 0x6d, 0x11, 0xaa, 0x6a, 0x8f, 0x6f, 0xd3, 0x11, 0x99, 0x3a, 0x37, 0x2c,
	0x77, 0xbc, 0xed, 0x79, 0x4d, 0x8f, 0xce, 0x6b, 0x61, 0x95, 0xa1, 0x90, 0xae, 0x32, 0x14, 0x97,
	0xab, 0x0c, 0xa5, 0x95, 0x55, 0x06, 0x6d, 0x55, 0x95, 0x41, 0x0f, 0x1f, 0xd7, 0x09, 0x27, 0xd1,
	0xe1, 0x1d, 0x56, 0x1c, 0xde, 0x13, 0xae, 0xbf, 0xbe, 0x8c, 0x50, 0x7e, 0x5d, 0x19, 0xa1, 0x22,
	0xbf, 0x97, 0x2e, 0x23, 0xa8, 0x82, 0x46, 0xa2, 0x8c, 0xb0, 0xb6, 0xa2, 0x8c, 0x70, 0xf7, 0x5d,
	0xca, 0x08, 0xc6, 0xb5, 0x65, 0x84, 0xf5, 0x58, 0x19, 0x21, 0x2a, 0x00, 0xa0, 0xff, 0x56, 0x00,
	0xd8, 0xb8, 0x61, 0x01, 0xe0, 0x5e, 0xaa, 0x00, 0xf0, 0x1e, 0xe8, 0xf4, 0x92, 0xab, 0x2b, 0xb6,
	0xac, 0x64, 0x68, 0x58, 0xa3, 0x97, 0x5c, 0x5e, 0xab, 0xd1, 0x36, 0x80, 0xeb, 0x0d, 0xe4, 0xe0,
	0x0b, 0x47, 0x56, 0x31, 0x34, 0xac, 0xb9, 0xde, 0x21, 0xe1, 0x47, 0x17, 0x4e, 0xfa, 0xec, 0xfc,
	0x60, 0xe9, 0xec, 0xfc, 0x69, 0xba, 0xb8, 0x50, 0x5f, 0x01, 0xaa, 0x7a, 0x4c, 0x0f, 0xa1, 0x7d,
	0xf7, 0x62, 0xc3, 0xdf, 0x73, 0xb0, 0xb1, 0xc2, 0x70, 0xea, 0xb9, 0x2f, 0xcc, 0x34, 0x8b, 0xe7,
	0xbe, 0xf9, 0x91, 0x2d, 0x1b, 0x56, 0x6a, 0xc4, 0x91, 0xed, 0xa1, 0xb8, 0x7b, 0x32, 0x32, 0x10,
	0xa7, 0x3b, 0xc1, 0x94, 0x0c, 0x2e, 0x39, 0x1e, 0x26, 0xbd, 0x2e, 0x46, 0x35, 0x28, 0x0d, 0xcf,
	0x88, 0xeb, 0x52, 0x47, 0xd2, 0xa4, 0x8a, 0xe7, 0xcd, 0xb7, 0xbc, 0xb0, 0x9a, 0xb0, 0x31, 0xb2,
	0x5d, 0x3a, 0x88, 0x0a, 0xa1, 0xea, 0x9a, 0x52, 0x94, 0x59, 0x6d, 0xb3, 0x31, 0x9e, 0x35, 0x3e,
	0xb7, 0x5d, 0x1a, 0x61, 0x2a, 0x93, 0xf4, 0xfa, 0x28, 0x2d, 0x42, 0x5f, 0x42, 0x8d, 0xba, 0x43,
	0x76, 0xe5, 0x73, 0x6a, 0x0d, 0x92, 0x06, 0xc3, 0x92, 0xc4, 0x96, 0xb0, 0x65, 0xce, 0x75, 0x12,
	0x46, 0x9f, 0xde, 0xc1, 0xf7, 0xe9, 0xca, 0x1e, 0xf4, 0x0c, 0xee, 0xf9, 0x0e, 0xb1, 0xdd, 0xb4,
	0x4d, 0xb5, 0xa5, 0xde, 0x17, 0x36, 0x4f, 0x44, 0x7f, 0xda, 0x1e, 0xf2, 0x97, 0xa4, 0x72, 0xc9,
	0x3c, 0x97, 0xd3, 0x4b, 0x1e, 0xb2, 0x7e, 0xde, 0x14, 0x21, 0x18, 0xdd, 0xbd, 0xc3, 0xd7, 0x4f,
	0x6d, 0x7e, 0xf5, 0x3e, 0x34, 0x60, 0x2d, 0xf9, 0xf1, 0x0f, 0xbf, 0xcb, 0x80, 0x1e, 0x3d, 0xff,
	0xa1, 0x32, 0x94, 0x5e, 0x74, 0xbf, 0xe8, 0x1e, 0xbf, 0xec, 0x1a, 0x77, 0xd0, 0x43, 0xd8, 0x6c,
	0x1f, 0xbf, 0xec, 0x1e, 0x75, 0xba, 0x5f, 0x0c, 0x4e, 0x9a, 0x5f, 0x1d, 0x1d, 0x37, 0xdb, 0x83,
	0x5e, 0xe7, 0x6b, 0xd3, 0xc8, 0xa0, 0x75, 0xa8, 0x46, 0x5d, 0x9f, 0xb7, 0xba, 0x7d, 0x23, 0x8b,
	0x0c, 0xa8, 0xbc, 0x38, 0x91, 0x82, 0xd6, 0x71, 0xdb, 0x6c, 0x19, 0x39, 0x84, 0x60, 0x2d, 0x52,
	0x52, 0xb2, 0x3c, 0xd2, 0x20, 0x7f, 0xdc, 0x6f, 0x36, 0x8d, 0x02, 0xda, 0x84, 0xf5, 0x50, 0x5f,
	0x18, 0x18, 0x60, 0xb3, 0x67, 0xf6, 0x8d, 0x22, 0x5a, 0x03, 0x08, 0xc5, 0xcf, 0x3b, 0x2d, 0xa3,
	0x84, 0x76, 0x60, 0x2b, 0xa9, 0xd6, 0xc7, 0xcd, 0x6e, 0xef, 0x79, 0xa7, 0xd7, 0xeb, 0x1c, 0x77,
	0x0d, 0x0d, 0xdd, 0x03, 0x23, 0xfa, 0xc8, 0xef, 0x9a, 0x7d, 0xf3, 0x65, 0xf3, 0x2b, 0x43, 0xff,
	0xf0, 0x8f, 0x19, 0xd8, 0x5c, 0xb9, 0x71, 0xa1, 0x0a, 0x68, 0xcd, 0x56, 0xcb, 0x3c, 0xe9, 0x9b,
	0x6d, 0xe3, 0x8e, 0x68, 0x61, 0xf3, 0x99, 0xd9, 0x12, 0xad, 0x0c, 0x02, 0x28, 0x1e, 0x77, 0x07,
	0xcd, 0x0e, 0x36, 0xb2, 0x62, 0xa2, 0x47, 0xc7, 0xbd, 0xbe, 0x91, 0x43, 0x55, 0xd0, 0xdb, 0xe6,
	0x51, 0xe7, 0x4b, 0x13, 0x9b, 0x6d, 0x23, 0x2f, 0x5c, 0x17, 0x06, 0x7a, 0xbd, 0x41, 0xdb, 0xec,
	0x76, 0xcc, 0xb6, 0x51, 0x10, 0x8e, 0x76, 0xba, 0x7d, 0x13, 0x77, 0x9b, 0x47, 0x03, 0x13, 0xe3,
	0x63, 0x6c, 0x14, 0xc5, 0xa8, 0x56, 0xb3, 0xdb, 0x32, 0x8f, 0x8e, 0xcc, 0xb6, 0x51, 0x3a, 0x74,
	0xa1, 0x6e, 0x7b, 0x8d, 0xe1, 0x99, 0xcd, 0xfc, 0x80, 0x93, 0xe1, 0x79, 0x83, 0xf8, 0x76, 0x83,
	0x04, 0x71, 0x06, 0x1f, 0xc6, 0x9f, 0x18, 0x4e, 0x44, 0x06, 0x3a, 0xc9, 0x7c, 0xfd, 0xf1, 0xd8,
	0xe6, 0x67, 0xd3, 0x53, 0x11, 0xf4, 0xfb, 0xa7, 0xcc, 0x1b, 0x12, 0xc2, 0xf6, 0x17, 0x56, 0x7e,
	0x46, 0x7c, 0x7b, 0x7f, 0xec, 0xed, 0x5f, 0x3c, 0xd9, 0x4f, 0xfe, 0x43, 0xc1, 0x69, 0x51, 0xa6,
	0xb0, 0x27, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x33, 0xe3, 0xc4, 0x69, 0x20, 0x00, 0x00,
}
