FROM golang:1.20.4-alpine

ENV PROJECT_PATH=/chirpstack-api

RUN apk add --no-cache make git bash protobuf protobuf-dev

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH

ENV GOBIN=/usr/local/bin
ENV PATH="${PATH}:${GOBIN}"

RUN cd go && go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc \
    github.com/bufbuild/buf/cmd/buf
