// Code generated by protoc-gen-go. DO NOT EDIT.
// source: handyrusty/hr.proto

package handyrusty

import (
	context "context"
	fmt "fmt"
	common "github.com/brocaar/chirpstack-api/go/v3/common"
	gw "github.com/brocaar/chirpstack-api/go/v3/gw"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamDeviceFramesLogCSVResponse struct {
	// Types that are valid to be assigned to Size:
	//	*StreamDeviceFramesLogCSVResponse_Current
	//	*StreamDeviceFramesLogCSVResponse_Total
	Size isStreamDeviceFramesLogCSVResponse_Size `protobuf_oneof:"size"`
	// Types that are valid to be assigned to Data:
	//	*StreamDeviceFramesLogCSVResponse_Rows
	//	*StreamDeviceFramesLogCSVResponse_Chunk
	Data                 isStreamDeviceFramesLogCSVResponse_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *StreamDeviceFramesLogCSVResponse) Reset()         { *m = StreamDeviceFramesLogCSVResponse{} }
func (m *StreamDeviceFramesLogCSVResponse) String() string { return proto.CompactTextString(m) }
func (*StreamDeviceFramesLogCSVResponse) ProtoMessage()    {}
func (*StreamDeviceFramesLogCSVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{0}
}

func (m *StreamDeviceFramesLogCSVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamDeviceFramesLogCSVResponse.Unmarshal(m, b)
}
func (m *StreamDeviceFramesLogCSVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamDeviceFramesLogCSVResponse.Marshal(b, m, deterministic)
}
func (m *StreamDeviceFramesLogCSVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamDeviceFramesLogCSVResponse.Merge(m, src)
}
func (m *StreamDeviceFramesLogCSVResponse) XXX_Size() int {
	return xxx_messageInfo_StreamDeviceFramesLogCSVResponse.Size(m)
}
func (m *StreamDeviceFramesLogCSVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamDeviceFramesLogCSVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamDeviceFramesLogCSVResponse proto.InternalMessageInfo

type isStreamDeviceFramesLogCSVResponse_Size interface {
	isStreamDeviceFramesLogCSVResponse_Size()
}

type StreamDeviceFramesLogCSVResponse_Current struct {
	Current uint32 `protobuf:"varint,1,opt,name=current,proto3,oneof"`
}

type StreamDeviceFramesLogCSVResponse_Total struct {
	Total uint32 `protobuf:"varint,2,opt,name=total,proto3,oneof"`
}

func (*StreamDeviceFramesLogCSVResponse_Current) isStreamDeviceFramesLogCSVResponse_Size() {}

func (*StreamDeviceFramesLogCSVResponse_Total) isStreamDeviceFramesLogCSVResponse_Size() {}

func (m *StreamDeviceFramesLogCSVResponse) GetSize() isStreamDeviceFramesLogCSVResponse_Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *StreamDeviceFramesLogCSVResponse) GetCurrent() uint32 {
	if x, ok := m.GetSize().(*StreamDeviceFramesLogCSVResponse_Current); ok {
		return x.Current
	}
	return 0
}

func (m *StreamDeviceFramesLogCSVResponse) GetTotal() uint32 {
	if x, ok := m.GetSize().(*StreamDeviceFramesLogCSVResponse_Total); ok {
		return x.Total
	}
	return 0
}

type isStreamDeviceFramesLogCSVResponse_Data interface {
	isStreamDeviceFramesLogCSVResponse_Data()
}

type StreamDeviceFramesLogCSVResponse_Rows struct {
	Rows uint32 `protobuf:"varint,3,opt,name=rows,proto3,oneof"`
}

type StreamDeviceFramesLogCSVResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

func (*StreamDeviceFramesLogCSVResponse_Rows) isStreamDeviceFramesLogCSVResponse_Data() {}

func (*StreamDeviceFramesLogCSVResponse_Chunk) isStreamDeviceFramesLogCSVResponse_Data() {}

func (m *StreamDeviceFramesLogCSVResponse) GetData() isStreamDeviceFramesLogCSVResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamDeviceFramesLogCSVResponse) GetRows() uint32 {
	if x, ok := m.GetData().(*StreamDeviceFramesLogCSVResponse_Rows); ok {
		return x.Rows
	}
	return 0
}

func (m *StreamDeviceFramesLogCSVResponse) GetChunk() []byte {
	if x, ok := m.GetData().(*StreamDeviceFramesLogCSVResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamDeviceFramesLogCSVResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamDeviceFramesLogCSVResponse_Current)(nil),
		(*StreamDeviceFramesLogCSVResponse_Total)(nil),
		(*StreamDeviceFramesLogCSVResponse_Rows)(nil),
		(*StreamDeviceFramesLogCSVResponse_Chunk)(nil),
	}
}

type GetDeviceFramesLogRequest struct {
	// you can specify offset (for pagination)
	Offset uint32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// you can specify rows limit
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// You can specify start DateTime point. format RFC3339: 2006-01-02T15:04:05.000Z
	Start string `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	// You can specify end DateTime point. format RFC3339: 2006-01-02T15:04:05.000Z
	End string `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	// Additional sql filters (key,value): allowed: direction,devEUI,mType,gw,devAddr
	Filters map[string]string `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// You can set the id to 0 if admin
	OrganizationId int64 `protobuf:"varint,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// here user sends his local timezone.
	Timezone             int64    `protobuf:"varint,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceFramesLogRequest) Reset()         { *m = GetDeviceFramesLogRequest{} }
func (m *GetDeviceFramesLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceFramesLogRequest) ProtoMessage()    {}
func (*GetDeviceFramesLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{1}
}

func (m *GetDeviceFramesLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceFramesLogRequest.Unmarshal(m, b)
}
func (m *GetDeviceFramesLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceFramesLogRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceFramesLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceFramesLogRequest.Merge(m, src)
}
func (m *GetDeviceFramesLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceFramesLogRequest.Size(m)
}
func (m *GetDeviceFramesLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceFramesLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceFramesLogRequest proto.InternalMessageInfo

func (m *GetDeviceFramesLogRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetDeviceFramesLogRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDeviceFramesLogRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetDeviceFramesLogRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *GetDeviceFramesLogRequest) GetFilters() map[string]string {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *GetDeviceFramesLogRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GetDeviceFramesLogRequest) GetTimezone() int64 {
	if m != nil {
		return m.Timezone
	}
	return 0
}

type GetDeviceFramesLogResponse struct {
	// total numner of selected rows
	ItemsTotal uint32 `protobuf:"varint,1,opt,name=items_total,json=itemsTotal,proto3" json:"items_total,omitempty"`
	// the array of selected device-frames logs
	Data                 []*DeviceFrameLog `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDeviceFramesLogResponse) Reset()         { *m = GetDeviceFramesLogResponse{} }
func (m *GetDeviceFramesLogResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceFramesLogResponse) ProtoMessage()    {}
func (*GetDeviceFramesLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{2}
}

func (m *GetDeviceFramesLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceFramesLogResponse.Unmarshal(m, b)
}
func (m *GetDeviceFramesLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceFramesLogResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceFramesLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceFramesLogResponse.Merge(m, src)
}
func (m *GetDeviceFramesLogResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceFramesLogResponse.Size(m)
}
func (m *GetDeviceFramesLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceFramesLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceFramesLogResponse proto.InternalMessageInfo

func (m *GetDeviceFramesLogResponse) GetItemsTotal() uint32 {
	if m != nil {
		return m.ItemsTotal
	}
	return 0
}

func (m *GetDeviceFramesLogResponse) GetData() []*DeviceFrameLog {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExecCommandRequest struct {
	// Gateway ID (HEX encoded).
	GatewayId string `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// command that will be executed on gateway (according to the gw config)
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCommandRequest) Reset()         { *m = ExecCommandRequest{} }
func (m *ExecCommandRequest) String() string { return proto.CompactTextString(m) }
func (*ExecCommandRequest) ProtoMessage()    {}
func (*ExecCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{3}
}

func (m *ExecCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCommandRequest.Unmarshal(m, b)
}
func (m *ExecCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCommandRequest.Marshal(b, m, deterministic)
}
func (m *ExecCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCommandRequest.Merge(m, src)
}
func (m *ExecCommandRequest) XXX_Size() int {
	return xxx_messageInfo_ExecCommandRequest.Size(m)
}
func (m *ExecCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCommandRequest proto.InternalMessageInfo

func (m *ExecCommandRequest) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *ExecCommandRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type GetFrameCountersRequest struct {
	// format RFC3339: 2006-01-02T15:04:05.000Z
	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// format RFC3339: 2006-01-02T15:04:05.000Z
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFrameCountersRequest) Reset()         { *m = GetFrameCountersRequest{} }
func (m *GetFrameCountersRequest) String() string { return proto.CompactTextString(m) }
func (*GetFrameCountersRequest) ProtoMessage()    {}
func (*GetFrameCountersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{4}
}

func (m *GetFrameCountersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFrameCountersRequest.Unmarshal(m, b)
}
func (m *GetFrameCountersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFrameCountersRequest.Marshal(b, m, deterministic)
}
func (m *GetFrameCountersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFrameCountersRequest.Merge(m, src)
}
func (m *GetFrameCountersRequest) XXX_Size() int {
	return xxx_messageInfo_GetFrameCountersRequest.Size(m)
}
func (m *GetFrameCountersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFrameCountersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFrameCountersRequest proto.InternalMessageInfo

func (m *GetFrameCountersRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetFrameCountersRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type GetFrameCountersResponse struct {
	// list counters with frame counters by type
	Counters             []*FrameCounters `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetFrameCountersResponse) Reset()         { *m = GetFrameCountersResponse{} }
func (m *GetFrameCountersResponse) String() string { return proto.CompactTextString(m) }
func (*GetFrameCountersResponse) ProtoMessage()    {}
func (*GetFrameCountersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{5}
}

func (m *GetFrameCountersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFrameCountersResponse.Unmarshal(m, b)
}
func (m *GetFrameCountersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFrameCountersResponse.Marshal(b, m, deterministic)
}
func (m *GetFrameCountersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFrameCountersResponse.Merge(m, src)
}
func (m *GetFrameCountersResponse) XXX_Size() int {
	return xxx_messageInfo_GetFrameCountersResponse.Size(m)
}
func (m *GetFrameCountersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFrameCountersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFrameCountersResponse proto.InternalMessageInfo

func (m *GetFrameCountersResponse) GetCounters() []*FrameCounters {
	if m != nil {
		return m.Counters
	}
	return nil
}

type GetFrameSpeedRequest struct {
	// format RFC3339: 2006-01-02T15:04:05.000Z
	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// format RFC3339: 2006-01-02T15:04:05.000Z
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFrameSpeedRequest) Reset()         { *m = GetFrameSpeedRequest{} }
func (m *GetFrameSpeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetFrameSpeedRequest) ProtoMessage()    {}
func (*GetFrameSpeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{6}
}

func (m *GetFrameSpeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFrameSpeedRequest.Unmarshal(m, b)
}
func (m *GetFrameSpeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFrameSpeedRequest.Marshal(b, m, deterministic)
}
func (m *GetFrameSpeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFrameSpeedRequest.Merge(m, src)
}
func (m *GetFrameSpeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetFrameSpeedRequest.Size(m)
}
func (m *GetFrameSpeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFrameSpeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFrameSpeedRequest proto.InternalMessageInfo

func (m *GetFrameSpeedRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetFrameSpeedRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type GetFrameSpeedResponse struct {
	// list counters with frames speed
	Counters             []*FrameSpeed `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFrameSpeedResponse) Reset()         { *m = GetFrameSpeedResponse{} }
func (m *GetFrameSpeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetFrameSpeedResponse) ProtoMessage()    {}
func (*GetFrameSpeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{7}
}

func (m *GetFrameSpeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFrameSpeedResponse.Unmarshal(m, b)
}
func (m *GetFrameSpeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFrameSpeedResponse.Marshal(b, m, deterministic)
}
func (m *GetFrameSpeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFrameSpeedResponse.Merge(m, src)
}
func (m *GetFrameSpeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetFrameSpeedResponse.Size(m)
}
func (m *GetFrameSpeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFrameSpeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFrameSpeedResponse proto.InternalMessageInfo

func (m *GetFrameSpeedResponse) GetCounters() []*FrameSpeed {
	if m != nil {
		return m.Counters
	}
	return nil
}

type GetDeviceCountersRequest struct {
	// Id (number). If Zero - all organisations (allowed for admin)
	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// format RFC3339: 2006-01-02T15:04:05.000Z
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// format RFC3339: 2006-01-02T15:04:05.000Z
	End string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// aggregation of the data: HOUR,DAY,WEEK,MONTH
	Aggregation          string   `protobuf:"bytes,4,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceCountersRequest) Reset()         { *m = GetDeviceCountersRequest{} }
func (m *GetDeviceCountersRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceCountersRequest) ProtoMessage()    {}
func (*GetDeviceCountersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{8}
}

func (m *GetDeviceCountersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceCountersRequest.Unmarshal(m, b)
}
func (m *GetDeviceCountersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceCountersRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceCountersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceCountersRequest.Merge(m, src)
}
func (m *GetDeviceCountersRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceCountersRequest.Size(m)
}
func (m *GetDeviceCountersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceCountersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceCountersRequest proto.InternalMessageInfo

func (m *GetDeviceCountersRequest) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GetDeviceCountersRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetDeviceCountersRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *GetDeviceCountersRequest) GetAggregation() string {
	if m != nil {
		return m.Aggregation
	}
	return ""
}

type GetDeviceCountersResponse struct {
	// id of the organisation that handles the devices
	OrganizationId       uint32            `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Counters             []*DeviceCounters `protobuf:"bytes,2,rep,name=counters,proto3" json:"counters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDeviceCountersResponse) Reset()         { *m = GetDeviceCountersResponse{} }
func (m *GetDeviceCountersResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceCountersResponse) ProtoMessage()    {}
func (*GetDeviceCountersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{9}
}

func (m *GetDeviceCountersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceCountersResponse.Unmarshal(m, b)
}
func (m *GetDeviceCountersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceCountersResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceCountersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceCountersResponse.Merge(m, src)
}
func (m *GetDeviceCountersResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceCountersResponse.Size(m)
}
func (m *GetDeviceCountersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceCountersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceCountersResponse proto.InternalMessageInfo

func (m *GetDeviceCountersResponse) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GetDeviceCountersResponse) GetCounters() []*DeviceCounters {
	if m != nil {
		return m.Counters
	}
	return nil
}

type GetGatewayCountersRequest struct {
	// Id (number). If Zero - all organisations (allowed for admin)
	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// format RFC3339: 2006-01-02T15:04:05.000Z
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// format RFC3339: 2006-01-02T15:04:05.000Z
	End string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// aggregation of the data: HOUR,DAY,WEEK,MONTH
	Aggregation          string   `protobuf:"bytes,4,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayCountersRequest) Reset()         { *m = GetGatewayCountersRequest{} }
func (m *GetGatewayCountersRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayCountersRequest) ProtoMessage()    {}
func (*GetGatewayCountersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{10}
}

func (m *GetGatewayCountersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayCountersRequest.Unmarshal(m, b)
}
func (m *GetGatewayCountersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayCountersRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayCountersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayCountersRequest.Merge(m, src)
}
func (m *GetGatewayCountersRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayCountersRequest.Size(m)
}
func (m *GetGatewayCountersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayCountersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayCountersRequest proto.InternalMessageInfo

func (m *GetGatewayCountersRequest) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GetGatewayCountersRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetGatewayCountersRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *GetGatewayCountersRequest) GetAggregation() string {
	if m != nil {
		return m.Aggregation
	}
	return ""
}

type GetGatewayCountersResponse struct {
	// id of the organisation that handles the devices
	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// log of counters
	Counters             []*DeviceCounters `protobuf:"bytes,2,rep,name=counters,proto3" json:"counters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetGatewayCountersResponse) Reset()         { *m = GetGatewayCountersResponse{} }
func (m *GetGatewayCountersResponse) String() string { return proto.CompactTextString(m) }
func (*GetGatewayCountersResponse) ProtoMessage()    {}
func (*GetGatewayCountersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{11}
}

func (m *GetGatewayCountersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayCountersResponse.Unmarshal(m, b)
}
func (m *GetGatewayCountersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayCountersResponse.Marshal(b, m, deterministic)
}
func (m *GetGatewayCountersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayCountersResponse.Merge(m, src)
}
func (m *GetGatewayCountersResponse) XXX_Size() int {
	return xxx_messageInfo_GetGatewayCountersResponse.Size(m)
}
func (m *GetGatewayCountersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayCountersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayCountersResponse proto.InternalMessageInfo

func (m *GetGatewayCountersResponse) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GetGatewayCountersResponse) GetCounters() []*DeviceCounters {
	if m != nil {
		return m.Counters
	}
	return nil
}

type GetVersionResponse struct {
	// ChirpStack Network Server version.
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionResponse) Reset()         { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()    {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{12}
}

func (m *GetVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionResponse.Unmarshal(m, b)
}
func (m *GetVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionResponse.Marshal(b, m, deterministic)
}
func (m *GetVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionResponse.Merge(m, src)
}
func (m *GetVersionResponse) XXX_Size() int {
	return xxx_messageInfo_GetVersionResponse.Size(m)
}
func (m *GetVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionResponse proto.InternalMessageInfo

func (m *GetVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// temp message just to check some thing
type GetBullshitResponse struct {
	// ChirpStack Network Server version.
	Xyu                  string   `protobuf:"bytes,1,opt,name=xyu,proto3" json:"xyu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBullshitResponse) Reset()         { *m = GetBullshitResponse{} }
func (m *GetBullshitResponse) String() string { return proto.CompactTextString(m) }
func (*GetBullshitResponse) ProtoMessage()    {}
func (*GetBullshitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{13}
}

func (m *GetBullshitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBullshitResponse.Unmarshal(m, b)
}
func (m *GetBullshitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBullshitResponse.Marshal(b, m, deterministic)
}
func (m *GetBullshitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBullshitResponse.Merge(m, src)
}
func (m *GetBullshitResponse) XXX_Size() int {
	return xxx_messageInfo_GetBullshitResponse.Size(m)
}
func (m *GetBullshitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBullshitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBullshitResponse proto.InternalMessageInfo

func (m *GetBullshitResponse) GetXyu() string {
	if m != nil {
		return m.Xyu
	}
	return ""
}

// counters
type DeviceCounters struct {
	// id of the organisation that handles the devices
	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Created at unix timestamp.
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Active count.
	ActiveCount uint32 `protobuf:"varint,3,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	// Inactive count.
	InactiveCount uint32 `protobuf:"varint,4,opt,name=inactive_count,json=inactiveCount,proto3" json:"inactive_count,omitempty"`
	// Never seen count.
	NeverSeenCount       uint32   `protobuf:"varint,5,opt,name=never_seen_count,json=neverSeenCount,proto3" json:"never_seen_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceCounters) Reset()         { *m = DeviceCounters{} }
func (m *DeviceCounters) String() string { return proto.CompactTextString(m) }
func (*DeviceCounters) ProtoMessage()    {}
func (*DeviceCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{14}
}

func (m *DeviceCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCounters.Unmarshal(m, b)
}
func (m *DeviceCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCounters.Marshal(b, m, deterministic)
}
func (m *DeviceCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCounters.Merge(m, src)
}
func (m *DeviceCounters) XXX_Size() int {
	return xxx_messageInfo_DeviceCounters.Size(m)
}
func (m *DeviceCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCounters.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCounters proto.InternalMessageInfo

func (m *DeviceCounters) GetOrganizationId() uint32 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *DeviceCounters) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *DeviceCounters) GetActiveCount() uint32 {
	if m != nil {
		return m.ActiveCount
	}
	return 0
}

func (m *DeviceCounters) GetInactiveCount() uint32 {
	if m != nil {
		return m.InactiveCount
	}
	return 0
}

func (m *DeviceCounters) GetNeverSeenCount() uint32 {
	if m != nil {
		return m.NeverSeenCount
	}
	return 0
}

type FrameCounters struct {
	// Date: the metrics counted for.
	Date int64 `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	// RxCnt: total recieved frames counted
	RxCnt uint32 `protobuf:"varint,2,opt,name=rx_cnt,json=rxCnt,proto3" json:"rx_cnt,omitempty"`
	// TxCnt: total transmitted frames counted
	TxCnt uint32 `protobuf:"varint,3,opt,name=tx_cnt,json=txCnt,proto3" json:"tx_cnt,omitempty"`
	// TotalCnt: both TxCnt and RxCnt counted
	TotalCnt uint32 `protobuf:"varint,4,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	// UnknownType:
	UnknownType uint32 `protobuf:"varint,5,opt,name=unknown_type,json=unknownType,proto3" json:"unknown_type,omitempty"`
	// JoinRequest
	JoinRequest uint32 `protobuf:"varint,6,opt,name=join_request,json=joinRequest,proto3" json:"join_request,omitempty"`
	// RejoinRequest
	RejoinRequest uint32 `protobuf:"varint,7,opt,name=rejoin_request,json=rejoinRequest,proto3" json:"rejoin_request,omitempty"`
	// JoinAccept
	JoinAccept uint32 `protobuf:"varint,8,opt,name=join_accept,json=joinAccept,proto3" json:"join_accept,omitempty"`
	// UnconfirmedDataUp
	UnconfirmedDataUp uint32 `protobuf:"varint,9,opt,name=unconfirmed_data_up,json=unconfirmedDataUp,proto3" json:"unconfirmed_data_up,omitempty"`
	// UnconfirmedDataDown
	UnconfirmedDataDown uint32 `protobuf:"varint,10,opt,name=unconfirmed_data_down,json=unconfirmedDataDown,proto3" json:"unconfirmed_data_down,omitempty"`
	// ConfirmedDataUp
	ConfirmedDataUp uint32 `protobuf:"varint,11,opt,name=confirmed_data_up,json=confirmedDataUp,proto3" json:"confirmed_data_up,omitempty"`
	// ConfirmedDataDown
	ConfirmedDataDown uint32 `protobuf:"varint,12,opt,name=confirmed_data_down,json=confirmedDataDown,proto3" json:"confirmed_data_down,omitempty"`
	// Proprietary
	Proprietary          uint32   `protobuf:"varint,13,opt,name=proprietary,proto3" json:"proprietary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameCounters) Reset()         { *m = FrameCounters{} }
func (m *FrameCounters) String() string { return proto.CompactTextString(m) }
func (*FrameCounters) ProtoMessage()    {}
func (*FrameCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{15}
}

func (m *FrameCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameCounters.Unmarshal(m, b)
}
func (m *FrameCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameCounters.Marshal(b, m, deterministic)
}
func (m *FrameCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameCounters.Merge(m, src)
}
func (m *FrameCounters) XXX_Size() int {
	return xxx_messageInfo_FrameCounters.Size(m)
}
func (m *FrameCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameCounters.DiscardUnknown(m)
}

var xxx_messageInfo_FrameCounters proto.InternalMessageInfo

func (m *FrameCounters) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *FrameCounters) GetRxCnt() uint32 {
	if m != nil {
		return m.RxCnt
	}
	return 0
}

func (m *FrameCounters) GetTxCnt() uint32 {
	if m != nil {
		return m.TxCnt
	}
	return 0
}

func (m *FrameCounters) GetTotalCnt() uint32 {
	if m != nil {
		return m.TotalCnt
	}
	return 0
}

func (m *FrameCounters) GetUnknownType() uint32 {
	if m != nil {
		return m.UnknownType
	}
	return 0
}

func (m *FrameCounters) GetJoinRequest() uint32 {
	if m != nil {
		return m.JoinRequest
	}
	return 0
}

func (m *FrameCounters) GetRejoinRequest() uint32 {
	if m != nil {
		return m.RejoinRequest
	}
	return 0
}

func (m *FrameCounters) GetJoinAccept() uint32 {
	if m != nil {
		return m.JoinAccept
	}
	return 0
}

func (m *FrameCounters) GetUnconfirmedDataUp() uint32 {
	if m != nil {
		return m.UnconfirmedDataUp
	}
	return 0
}

func (m *FrameCounters) GetUnconfirmedDataDown() uint32 {
	if m != nil {
		return m.UnconfirmedDataDown
	}
	return 0
}

func (m *FrameCounters) GetConfirmedDataUp() uint32 {
	if m != nil {
		return m.ConfirmedDataUp
	}
	return 0
}

func (m *FrameCounters) GetConfirmedDataDown() uint32 {
	if m != nil {
		return m.ConfirmedDataDown
	}
	return 0
}

func (m *FrameCounters) GetProprietary() uint32 {
	if m != nil {
		return m.Proprietary
	}
	return 0
}

type FrameSpeed struct {
	// T: Created at timestamp (unix)
	T int64 `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	// Y: TotalCnt: both TxCnt and RxCnt frames counted for the amount of time
	Y                    uint32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameSpeed) Reset()         { *m = FrameSpeed{} }
func (m *FrameSpeed) String() string { return proto.CompactTextString(m) }
func (*FrameSpeed) ProtoMessage()    {}
func (*FrameSpeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{16}
}

func (m *FrameSpeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameSpeed.Unmarshal(m, b)
}
func (m *FrameSpeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameSpeed.Marshal(b, m, deterministic)
}
func (m *FrameSpeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameSpeed.Merge(m, src)
}
func (m *FrameSpeed) XXX_Size() int {
	return xxx_messageInfo_FrameSpeed.Size(m)
}
func (m *FrameSpeed) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameSpeed.DiscardUnknown(m)
}

var xxx_messageInfo_FrameSpeed proto.InternalMessageInfo

func (m *FrameSpeed) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *FrameSpeed) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// for storage
type DeviceFrameLog struct {
	// RX (uplink -recieved from devices) or TX (downlink - transmitted from NS)
	Direction string `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	DateTime  string `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Date      string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	MType     string `protobuf:"bytes,4,opt,name=mType,proto3" json:"mType,omitempty"`
	DevAddr   string `protobuf:"bytes,5,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	DevEUI    string `protobuf:"bytes,6,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	// params from base station with best SNR
	RxRssi    int32   `protobuf:"varint,7,opt,name=rxRssi,proto3" json:"rxRssi,omitempty"`
	RxSnr     float64 `protobuf:"fixed64,8,opt,name=rx_snr,json=rxSnr,proto3" json:"rx_snr,omitempty"`
	RxChannel uint32  `protobuf:"varint,9,opt,name=rx_channel,json=rxChannel,proto3" json:"rx_channel,omitempty"`
	RxRfChain uint32  `protobuf:"varint,10,opt,name=rx_rf_chain,json=rxRfChain,proto3" json:"rx_rf_chain,omitempty"`
	// id of base station with best SNR
	Gw string `protobuf:"bytes,11,opt,name=gw,proto3" json:"gw,omitempty"`
	// json-string
	TxInfo string `protobuf:"bytes,12,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RXInfo an array with info from BS recieved the frame
	RxInfo []*RXInfo `protobuf:"bytes,13,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// json-string with LORA payload
	PhyPayloadJSON       string   `protobuf:"bytes,14,opt,name=phy_payloadJSON,json=PhyPayloadJson,proto3" json:"phy_payloadJSON,omitempty"`
	Airtime              float64  `protobuf:"fixed64,15,opt,name=airtime,proto3" json:"airtime,omitempty"`
	Esp                  float64  `protobuf:"fixed64,16,opt,name=esp,proto3" json:"esp,omitempty"`
	Late                 uint32   `protobuf:"varint,17,opt,name=late,proto3" json:"late,omitempty"`
	FrmPayload           string   `protobuf:"bytes,18,opt,name=frm_payload,json=frmPayload,proto3" json:"frm_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceFrameLog) Reset()         { *m = DeviceFrameLog{} }
func (m *DeviceFrameLog) String() string { return proto.CompactTextString(m) }
func (*DeviceFrameLog) ProtoMessage()    {}
func (*DeviceFrameLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{17}
}

func (m *DeviceFrameLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceFrameLog.Unmarshal(m, b)
}
func (m *DeviceFrameLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceFrameLog.Marshal(b, m, deterministic)
}
func (m *DeviceFrameLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceFrameLog.Merge(m, src)
}
func (m *DeviceFrameLog) XXX_Size() int {
	return xxx_messageInfo_DeviceFrameLog.Size(m)
}
func (m *DeviceFrameLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceFrameLog.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceFrameLog proto.InternalMessageInfo

func (m *DeviceFrameLog) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *DeviceFrameLog) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *DeviceFrameLog) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *DeviceFrameLog) GetMType() string {
	if m != nil {
		return m.MType
	}
	return ""
}

func (m *DeviceFrameLog) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *DeviceFrameLog) GetDevEUI() string {
	if m != nil {
		return m.DevEUI
	}
	return ""
}

func (m *DeviceFrameLog) GetRxRssi() int32 {
	if m != nil {
		return m.RxRssi
	}
	return 0
}

func (m *DeviceFrameLog) GetRxSnr() float64 {
	if m != nil {
		return m.RxSnr
	}
	return 0
}

func (m *DeviceFrameLog) GetRxChannel() uint32 {
	if m != nil {
		return m.RxChannel
	}
	return 0
}

func (m *DeviceFrameLog) GetRxRfChain() uint32 {
	if m != nil {
		return m.RxRfChain
	}
	return 0
}

func (m *DeviceFrameLog) GetGw() string {
	if m != nil {
		return m.Gw
	}
	return ""
}

func (m *DeviceFrameLog) GetTxInfo() string {
	if m != nil {
		return m.TxInfo
	}
	return ""
}

func (m *DeviceFrameLog) GetRxInfo() []*RXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

func (m *DeviceFrameLog) GetPhyPayloadJSON() string {
	if m != nil {
		return m.PhyPayloadJSON
	}
	return ""
}

func (m *DeviceFrameLog) GetAirtime() float64 {
	if m != nil {
		return m.Airtime
	}
	return 0
}

func (m *DeviceFrameLog) GetEsp() float64 {
	if m != nil {
		return m.Esp
	}
	return 0
}

func (m *DeviceFrameLog) GetLate() uint32 {
	if m != nil {
		return m.Late
	}
	return 0
}

func (m *DeviceFrameLog) GetFrmPayload() string {
	if m != nil {
		return m.FrmPayload
	}
	return ""
}

// for RXInfo item in uplink frames
type RXInfo struct {
	// GatewayID
	GatewayID         string               `protobuf:"bytes,1,opt,name=GatewayID,json=gateway_id,proto3" json:"GatewayID,omitempty"`
	Rssi              int32                `protobuf:"varint,2,opt,name=Rssi,json=rssi,proto3" json:"Rssi,omitempty"`
	LoraSnr           float64              `protobuf:"fixed64,3,opt,name=LoraSnr,json=lora_snr,proto3" json:"LoraSnr,omitempty"`
	Channel           uint32               `protobuf:"varint,4,opt,name=Channel,json=channel,proto3" json:"Channel,omitempty"`
	RfChain           uint32               `protobuf:"varint,5,opt,name=RfChain,json=rf_chain,proto3" json:"RfChain,omitempty"`
	Board             uint32               `protobuf:"varint,6,opt,name=Board,json=board,proto3" json:"Board,omitempty"`
	Antenna           uint32               `protobuf:"varint,7,opt,name=Antenna,json=antenna,proto3" json:"Antenna,omitempty"`
	Location          *common.Location     `protobuf:"bytes,8,opt,name=Location,json=location,proto3" json:"Location,omitempty"`
	FineTimestampType gw.FineTimestampType `protobuf:"varint,9,opt,name=FineTimestampType,proto3,enum=gw.FineTimestampType" json:"FineTimestampType,omitempty"`
	GpsTimestamp      string               `protobuf:"bytes,10,opt,name=GpsTimestamp,json=gps_timestamp,proto3" json:"GpsTimestamp,omitempty"`
	FineTimestamp     string               `protobuf:"bytes,11,opt,name=FineTimestamp,json=fine_timestamp,proto3" json:"FineTimestamp,omitempty"`
	Context           string               `protobuf:"bytes,12,opt,name=Context,json=context,proto3" json:"Context,omitempty"`
	// Unique and random ID which can be used to correlate the uplink across multiple logs.
	UplinkID             string   `protobuf:"bytes,13,opt,name=UplinkID,json=uplink_id,proto3" json:"UplinkID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RXInfo) Reset()         { *m = RXInfo{} }
func (m *RXInfo) String() string { return proto.CompactTextString(m) }
func (*RXInfo) ProtoMessage()    {}
func (*RXInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d7a55acfa39588, []int{18}
}

func (m *RXInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RXInfo.Unmarshal(m, b)
}
func (m *RXInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RXInfo.Marshal(b, m, deterministic)
}
func (m *RXInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RXInfo.Merge(m, src)
}
func (m *RXInfo) XXX_Size() int {
	return xxx_messageInfo_RXInfo.Size(m)
}
func (m *RXInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RXInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RXInfo proto.InternalMessageInfo

func (m *RXInfo) GetGatewayID() string {
	if m != nil {
		return m.GatewayID
	}
	return ""
}

func (m *RXInfo) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *RXInfo) GetLoraSnr() float64 {
	if m != nil {
		return m.LoraSnr
	}
	return 0
}

func (m *RXInfo) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *RXInfo) GetRfChain() uint32 {
	if m != nil {
		return m.RfChain
	}
	return 0
}

func (m *RXInfo) GetBoard() uint32 {
	if m != nil {
		return m.Board
	}
	return 0
}

func (m *RXInfo) GetAntenna() uint32 {
	if m != nil {
		return m.Antenna
	}
	return 0
}

func (m *RXInfo) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RXInfo) GetFineTimestampType() gw.FineTimestampType {
	if m != nil {
		return m.FineTimestampType
	}
	return gw.FineTimestampType_NONE
}

func (m *RXInfo) GetGpsTimestamp() string {
	if m != nil {
		return m.GpsTimestamp
	}
	return ""
}

func (m *RXInfo) GetFineTimestamp() string {
	if m != nil {
		return m.FineTimestamp
	}
	return ""
}

func (m *RXInfo) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *RXInfo) GetUplinkID() string {
	if m != nil {
		return m.UplinkID
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamDeviceFramesLogCSVResponse)(nil), "hr.StreamDeviceFramesLogCSVResponse")
	proto.RegisterType((*GetDeviceFramesLogRequest)(nil), "hr.GetDeviceFramesLogRequest")
	proto.RegisterMapType((map[string]string)(nil), "hr.GetDeviceFramesLogRequest.FiltersEntry")
	proto.RegisterType((*GetDeviceFramesLogResponse)(nil), "hr.GetDeviceFramesLogResponse")
	proto.RegisterType((*ExecCommandRequest)(nil), "hr.ExecCommandRequest")
	proto.RegisterType((*GetFrameCountersRequest)(nil), "hr.GetFrameCountersRequest")
	proto.RegisterType((*GetFrameCountersResponse)(nil), "hr.GetFrameCountersResponse")
	proto.RegisterType((*GetFrameSpeedRequest)(nil), "hr.GetFrameSpeedRequest")
	proto.RegisterType((*GetFrameSpeedResponse)(nil), "hr.GetFrameSpeedResponse")
	proto.RegisterType((*GetDeviceCountersRequest)(nil), "hr.GetDeviceCountersRequest")
	proto.RegisterType((*GetDeviceCountersResponse)(nil), "hr.GetDeviceCountersResponse")
	proto.RegisterType((*GetGatewayCountersRequest)(nil), "hr.GetGatewayCountersRequest")
	proto.RegisterType((*GetGatewayCountersResponse)(nil), "hr.GetGatewayCountersResponse")
	proto.RegisterType((*GetVersionResponse)(nil), "hr.GetVersionResponse")
	proto.RegisterType((*GetBullshitResponse)(nil), "hr.GetBullshitResponse")
	proto.RegisterType((*DeviceCounters)(nil), "hr.DeviceCounters")
	proto.RegisterType((*FrameCounters)(nil), "hr.FrameCounters")
	proto.RegisterType((*FrameSpeed)(nil), "hr.FrameSpeed")
	proto.RegisterType((*DeviceFrameLog)(nil), "hr.DeviceFrameLog")
	proto.RegisterType((*RXInfo)(nil), "hr.RXInfo")
}

func init() {
	proto.RegisterFile("handyrusty/hr.proto", fileDescriptor_97d7a55acfa39588)
}

var fileDescriptor_97d7a55acfa39588 = []byte{
	// 1640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x72, 0x1b, 0xb9,
	0x11, 0xf6, 0x90, 0xa2, 0xc8, 0x69, 0x8a, 0xb4, 0x04, 0xd9, 0xde, 0x11, 0x6d, 0xd9, 0x5a, 0x6e,
	0x1c, 0xab, 0x5c, 0x59, 0x32, 0xa5, 0xcd, 0x21, 0xb5, 0x87, 0xad, 0x92, 0x25, 0x5b, 0x56, 0xca,
	0xc9, 0x6e, 0x8d, 0xac, 0xad, 0x54, 0x2e, 0x53, 0xd0, 0x0c, 0x48, 0x4e, 0x44, 0x02, 0x13, 0x0c,
	0x86, 0xe4, 0xf8, 0x1d, 0x92, 0x53, 0x8e, 0x79, 0x89, 0xdc, 0xf2, 0x10, 0x79, 0x86, 0x3c, 0x42,
	0x9e, 0x21, 0x85, 0x06, 0x66, 0xc4, 0x3f, 0x65, 0x37, 0x87, 0x54, 0xed, 0x69, 0xa6, 0xbf, 0x6e,
	0x34, 0x3e, 0x74, 0x37, 0x1a, 0x00, 0xec, 0x8f, 0x28, 0x8f, 0x72, 0x99, 0xa5, 0x2a, 0xef, 0x8f,
	0x64, 0x2f, 0x91, 0x42, 0x09, 0x52, 0x19, 0xc9, 0xce, 0x8b, 0xa1, 0x10, 0xc3, 0x31, 0xeb, 0x23,
	0x72, 0x93, 0x0d, 0xfa, 0x2a, 0x9e, 0xb0, 0x54, 0xd1, 0x49, 0x62, 0x8c, 0x3a, 0x4f, 0x57, 0x0d,
	0xd8, 0x24, 0x51, 0xb9, 0x55, 0x1e, 0xac, 0x2a, 0x29, 0x2f, 0x54, 0xfb, 0xa1, 0x98, 0x4c, 0x04,
	0xef, 0x9b, 0x8f, 0x05, 0x9b, 0xc3, 0x59, 0x7f, 0x38, 0x33, 0x42, 0xf7, 0xaf, 0x0e, 0x1c, 0x5d,
	0x29, 0xc9, 0xe8, 0xe4, 0x9c, 0x4d, 0xe3, 0x90, 0xbd, 0x93, 0x74, 0xc2, 0xd2, 0x0f, 0x62, 0x78,
	0x76, 0xf5, 0xbd, 0xcf, 0xd2, 0x44, 0xf0, 0x94, 0x91, 0x0e, 0xd4, 0xc3, 0x4c, 0x4a, 0xc6, 0x95,
	0xe7, 0x1c, 0x39, 0xc7, 0xad, 0xf7, 0x0f, 0xfc, 0x02, 0x20, 0x4f, 0xa0, 0xa6, 0x84, 0xa2, 0x63,
	0xaf, 0x62, 0x35, 0x46, 0x24, 0x8f, 0x60, 0x4b, 0x8a, 0x59, 0xea, 0x55, 0x11, 0x76, 0x7c, 0x94,
	0xb4, 0x75, 0x38, 0xca, 0xf8, 0xad, 0xb7, 0x75, 0xe4, 0x1c, 0xef, 0xbc, 0x77, 0x7c, 0x23, 0xbe,
	0xd9, 0x86, 0xad, 0x34, 0xfe, 0xc4, 0xf4, 0x37, 0xa2, 0x8a, 0x76, 0xff, 0x51, 0x81, 0x83, 0x0b,
	0xa6, 0x56, 0x38, 0xf9, 0xec, 0x4f, 0x19, 0x4b, 0xf5, 0x9c, 0xdb, 0x62, 0x30, 0x48, 0x99, 0xa5,
	0xe3, 0x5b, 0x89, 0x3c, 0x82, 0xda, 0x38, 0x9e, 0xc4, 0xca, 0x70, 0xf1, 0x8d, 0xa0, 0xd1, 0x54,
	0x51, 0xa9, 0x90, 0x8a, 0xeb, 0x1b, 0x81, 0xec, 0x42, 0x95, 0xf1, 0x08, 0x79, 0xb8, 0xbe, 0xfe,
	0x25, 0xe7, 0x50, 0x1f, 0xc4, 0x63, 0xc5, 0x64, 0xea, 0xd5, 0x8e, 0xaa, 0xc7, 0xcd, 0x93, 0xd7,
	0xbd, 0x91, 0xec, 0xdd, 0xcb, 0xa2, 0xf7, 0xce, 0x18, 0xbf, 0xe5, 0x4a, 0xe6, 0x7e, 0x31, 0x94,
	0xbc, 0x82, 0x87, 0x42, 0x0e, 0x29, 0x8f, 0x3f, 0x51, 0x15, 0x0b, 0x1e, 0xc4, 0x91, 0xb7, 0x7d,
	0xe4, 0x1c, 0x57, 0xfd, 0xf6, 0x22, 0x7c, 0x19, 0x91, 0x0e, 0x34, 0x74, 0x9a, 0x3f, 0x09, 0xce,
	0xbc, 0x3a, 0x5a, 0x94, 0x72, 0xe7, 0x6b, 0xd8, 0x59, 0xf4, 0xae, 0xc9, 0xde, 0xb2, 0x1c, 0x57,
	0xeb, 0xfa, 0xfa, 0x57, 0x2f, 0x6a, 0x4a, 0xc7, 0x19, 0xc3, 0xa5, 0xba, 0xbe, 0x11, 0xbe, 0xae,
	0xfc, 0xda, 0xe9, 0x32, 0xe8, 0x6c, 0xe2, 0x6c, 0x53, 0xf9, 0x02, 0x9a, 0xb1, 0x62, 0x93, 0x34,
	0x30, 0x49, 0x33, 0xf1, 0x03, 0x84, 0x3e, 0x62, 0xde, 0x7e, 0x6e, 0x32, 0xe0, 0x55, 0x30, 0x04,
	0x44, 0x87, 0x60, 0xc1, 0x97, 0x76, 0x65, 0x32, 0xf4, 0x5b, 0x20, 0x6f, 0xe7, 0x2c, 0x3c, 0x13,
	0x93, 0x09, 0xe5, 0x51, 0x91, 0x99, 0x43, 0x80, 0x21, 0x55, 0x6c, 0x46, 0x73, 0xbd, 0x70, 0xc3,
	0xd7, 0xb5, 0xc8, 0x65, 0x44, 0x3c, 0xa8, 0x87, 0x66, 0x80, 0xe5, 0x5d, 0x88, 0xdd, 0x53, 0xf8,
	0xec, 0x82, 0x29, 0x9c, 0xe3, 0x4c, 0x64, 0x5c, 0x2f, 0xbd, 0xf0, 0x59, 0xe6, 0xcf, 0xd9, 0x90,
	0xbf, 0x4a, 0x99, 0xbf, 0xee, 0x25, 0x78, 0xeb, 0x2e, 0xec, 0xb2, 0xbf, 0x84, 0x46, 0x68, 0x31,
	0xcf, 0xc1, 0x95, 0xed, 0xe9, 0x95, 0x2d, 0x1b, 0x97, 0x26, 0xdd, 0x6f, 0xe0, 0x51, 0xe1, 0xea,
	0x2a, 0x61, 0x2c, 0xfa, 0x5f, 0xa9, 0x9c, 0xc1, 0xe3, 0x95, 0xf1, 0x96, 0xc7, 0xeb, 0x35, 0x1e,
	0xed, 0x92, 0x87, 0xb1, 0xbc, 0x23, 0xf1, 0x67, 0x07, 0x17, 0x64, 0xa2, 0xbf, 0x1a, 0x94, 0x0d,
	0x65, 0x66, 0x72, 0xb9, 0x5a, 0x66, 0x25, 0xe5, 0xca, 0x06, 0xca, 0xd5, 0xbb, 0xea, 0x3f, 0x82,
	0x26, 0x1d, 0x0e, 0x25, 0x1b, 0xe2, 0x40, 0xbb, 0x2f, 0x16, 0xa1, 0xae, 0x5a, 0xd8, 0x92, 0x6b,
	0x01, 0xfe, 0xd1, 0x7c, 0x7a, 0x0b, 0x11, 0x58, 0xab, 0xb1, 0x0d, 0xa9, 0xf8, 0x8b, 0x83, 0xd3,
	0x5e, 0x98, 0x1a, 0xfa, 0x09, 0x84, 0x21, 0xc3, 0xfd, 0xb5, 0xc6, 0xe7, 0xff, 0x1d, 0x87, 0x1e,
	0x90, 0x0b, 0xa6, 0xbe, 0x67, 0x32, 0x8d, 0x05, 0x2f, 0xa7, 0xf3, 0xa0, 0x3e, 0x35, 0x90, 0x2d,
	0xc9, 0x42, 0xec, 0xbe, 0x82, 0xfd, 0x0b, 0xa6, 0xde, 0x64, 0xe3, 0x71, 0x3a, 0x8a, 0x55, 0x39,
	0x60, 0x17, 0xaa, 0xf3, 0x3c, 0x2b, 0x3a, 0xc9, 0x3c, 0xcf, 0xba, 0xff, 0x74, 0xa0, 0xbd, 0x3c,
	0xeb, 0x8f, 0x5f, 0xc4, 0x21, 0x40, 0x28, 0x19, 0x55, 0x2c, 0x0a, 0x68, 0xd1, 0x75, 0x5d, 0x8b,
	0x9c, 0x2a, 0xf2, 0x39, 0xec, 0xd0, 0x50, 0xc5, 0x53, 0x16, 0xe0, 0x32, 0xcc, 0x59, 0xe0, 0x37,
	0x0d, 0x86, 0xb3, 0x91, 0x97, 0xd0, 0x8e, 0xf9, 0x92, 0xd1, 0x16, 0x1a, 0xb5, 0x0a, 0xd4, 0x98,
	0x1d, 0xc3, 0x2e, 0x67, 0x53, 0x26, 0x83, 0x94, 0x31, 0x6e, 0x0d, 0x6b, 0x86, 0x12, 0xe2, 0x57,
	0x8c, 0x71, 0xb4, 0xec, 0xfe, 0xab, 0x0a, 0xad, 0xa5, 0x6d, 0x4d, 0x08, 0x76, 0x34, 0x86, 0x4b,
	0xa8, 0x62, 0xf7, 0x62, 0xe4, 0x31, 0x6c, 0xcb, 0x79, 0x10, 0xf2, 0xf2, 0xa8, 0x90, 0xf3, 0x33,
	0xae, 0x34, 0xac, 0x0c, 0x6c, 0xa8, 0xd6, 0x14, 0xc2, 0x4f, 0xc1, 0xc5, 0x76, 0x89, 0x1a, 0xc3,
	0xaf, 0x81, 0x80, 0x56, 0x7e, 0x0e, 0x3b, 0x19, 0xbf, 0xe5, 0x62, 0xc6, 0x03, 0x95, 0x27, 0xcc,
	0xd2, 0x6a, 0x5a, 0xec, 0x63, 0x9e, 0x30, 0x6d, 0xf2, 0x47, 0x11, 0xf3, 0x40, 0x9a, 0xaa, 0xc5,
	0x03, 0xa1, 0xe5, 0x37, 0x35, 0x56, 0x14, 0xf2, 0x4b, 0x68, 0x4b, 0xb6, 0x64, 0x54, 0x37, 0x71,
	0x30, 0x68, 0x61, 0xf6, 0x02, 0x70, 0x54, 0x40, 0xc3, 0x90, 0x25, 0xca, 0x6b, 0x98, 0xf6, 0xad,
	0xa1, 0x53, 0x44, 0x48, 0x0f, 0xf6, 0x33, 0x1e, 0x0a, 0x3e, 0x88, 0xe5, 0x84, 0x45, 0x81, 0x6e,
	0xd5, 0x41, 0x96, 0x78, 0x2e, 0x1a, 0xee, 0x2d, 0xa8, 0xce, 0xa9, 0xa2, 0xd7, 0x09, 0x39, 0x81,
	0xc7, 0x6b, 0xf6, 0x91, 0x98, 0x71, 0x0f, 0x70, 0xc4, 0xfe, 0xca, 0x88, 0x73, 0x31, 0xe3, 0xe4,
	0x35, 0xec, 0xad, 0xcf, 0xd0, 0x44, 0xfb, 0x87, 0xab, 0xfe, 0x7b, 0xb0, 0xbf, 0xc9, 0xfb, 0x8e,
	0xe1, 0xb3, 0xee, 0xfb, 0x08, 0x9a, 0x89, 0x14, 0x89, 0x8c, 0x99, 0xa2, 0x32, 0xf7, 0x5a, 0x26,
	0x52, 0x0b, 0x50, 0xf7, 0x18, 0xe0, 0xae, 0x5d, 0x92, 0x1d, 0x70, 0x94, 0xcd, 0xac, 0xa3, 0xb4,
	0x94, 0xdb, 0x8c, 0x3a, 0x79, 0xf7, 0xdf, 0xd5, 0xa2, 0xb2, 0x8b, 0xb3, 0x8b, 0x3c, 0x03, 0x37,
	0x8a, 0x25, 0x0b, 0xd5, 0xdd, 0x8e, 0xb9, 0x03, 0x74, 0x9e, 0x75, 0x75, 0x04, 0xfa, 0x1c, 0xb6,
	0x8d, 0xa2, 0xa1, 0x81, 0x8f, 0xf1, 0x84, 0x95, 0x65, 0x64, 0x9a, 0x85, 0x29, 0xa3, 0x47, 0x50,
	0x9b, 0xe8, 0x0c, 0xdb, 0x3e, 0x61, 0x04, 0x72, 0x00, 0x8d, 0x88, 0x4d, 0x03, 0x1a, 0x45, 0x12,
	0xab, 0xc1, 0xf5, 0xeb, 0x11, 0x9b, 0x9e, 0x46, 0x91, 0xd4, 0x37, 0x97, 0x88, 0x4d, 0xdf, 0x5e,
	0x5f, 0x62, 0x0d, 0xb8, 0xbe, 0x95, 0x34, 0x2e, 0xe7, 0x7e, 0x9a, 0xc6, 0x98, 0xf6, 0x9a, 0x6f,
	0x25, 0x5b, 0xa7, 0x29, 0x97, 0x98, 0x6a, 0x47, 0xd7, 0xe9, 0x15, 0x97, 0x7a, 0xdf, 0xe9, 0xf2,
	0x1d, 0x51, 0xce, 0xd9, 0xd8, 0x26, 0xd7, 0x95, 0xf3, 0x33, 0x03, 0x90, 0xe7, 0xd0, 0x94, 0xf3,
	0x40, 0x0e, 0xb4, 0x45, 0x5c, 0xa4, 0xd2, 0x95, 0x73, 0x7f, 0x70, 0xa6, 0x01, 0xd2, 0x86, 0xca,
	0x70, 0x86, 0x19, 0x73, 0xfd, 0xca, 0x70, 0x46, 0x3e, 0x83, 0xba, 0x9a, 0x07, 0x31, 0x1f, 0x08,
	0x4c, 0x8c, 0xeb, 0x6f, 0xab, 0xf9, 0x25, 0x1f, 0x08, 0xf2, 0x05, 0xd4, 0xa5, 0x55, 0xb4, 0xb0,
	0x47, 0x81, 0xee, 0x51, 0xfe, 0xef, 0xb5, 0x52, 0x73, 0x44, 0xa3, 0x57, 0xf0, 0x30, 0x19, 0xe5,
	0x41, 0x42, 0xf3, 0xb1, 0xa0, 0xd1, 0x6f, 0xae, 0xbe, 0xfd, 0x9d, 0xd7, 0x46, 0x2f, 0xed, 0xef,
	0x46, 0xf9, 0x77, 0x16, 0x4d, 0x05, 0xd7, 0xcd, 0x8a, 0xc6, 0x12, 0x83, 0xfb, 0x10, 0x57, 0x53,
	0x88, 0xd8, 0x87, 0xd3, 0xc4, 0xdb, 0x45, 0x54, 0xff, 0xea, 0x68, 0x8f, 0x75, 0xb4, 0xf7, 0x90,
	0x3b, 0xfe, 0xeb, 0xe2, 0x1f, 0xc8, 0x49, 0x31, 0x91, 0x47, 0x70, 0x12, 0x18, 0xc8, 0x89, 0x9d,
	0xa4, 0xfb, 0xf7, 0x2a, 0x6c, 0x1b, 0x72, 0xe4, 0x10, 0x5c, 0xdb, 0xa2, 0x2f, 0xcf, 0x6d, 0xa2,
	0x17, 0x6e, 0x26, 0xda, 0x3d, 0x46, 0xbb, 0x82, 0xd1, 0xde, 0x92, 0x3a, 0xd6, 0x07, 0x50, 0xff,
	0x20, 0x24, 0xbd, 0xe2, 0x12, 0x73, 0xec, 0xf8, 0x8d, 0xb1, 0x90, 0x54, 0x07, 0x5f, 0x33, 0xb7,
	0xb1, 0xb5, 0xdb, 0xbf, 0x6e, 0x63, 0xaf, 0x07, 0xd9, 0xa8, 0xda, 0x8d, 0xdf, 0x28, 0xc2, 0xae,
	0x8b, 0xe3, 0x8d, 0xa0, 0x32, 0xb2, 0xdb, 0xbd, 0x76, 0xa3, 0x05, 0xed, 0xea, 0x94, 0x2b, 0xc6,
	0x39, 0xb5, 0x3b, 0xbc, 0x4e, 0x8d, 0x48, 0x7e, 0x01, 0x8d, 0x0f, 0x22, 0x34, 0xe7, 0x8e, 0xce,
	0x76, 0xf3, 0x64, 0xb7, 0x67, 0x2f, 0xee, 0x05, 0xae, 0x29, 0x99, 0x3f, 0x72, 0x06, 0x7b, 0xef,
	0x62, 0x8e, 0xa5, 0x89, 0x2f, 0x05, 0x2c, 0x43, 0x5d, 0x09, 0xed, 0x93, 0xc7, 0xbd, 0xe1, 0xac,
	0xb7, 0xa6, 0xf4, 0xd7, 0xed, 0xc9, 0x17, 0xb0, 0x73, 0x91, 0xa4, 0x25, 0x86, 0x95, 0xe2, 0xfa,
	0xad, 0x61, 0x92, 0x06, 0xe5, 0x13, 0x84, 0xbc, 0x84, 0xd6, 0xd2, 0x48, 0x5b, 0x38, 0xed, 0x41,
	0xcc, 0xd9, 0x82, 0x99, 0x8e, 0x91, 0xe0, 0x8a, 0xcd, 0x95, 0x2d, 0xa2, 0x7a, 0x68, 0x44, 0xf2,
	0x14, 0x1a, 0xd7, 0xc9, 0x38, 0xe6, 0xb7, 0x97, 0xe7, 0xb8, 0xa1, 0x5d, 0xdf, 0xcd, 0x50, 0x0e,
	0xe2, 0xe8, 0xe4, 0x6f, 0x35, 0xd8, 0x7b, 0xaf, 0xdf, 0x45, 0xbe, 0x7e, 0x17, 0x5d, 0x31, 0xa9,
	0xf7, 0x2b, 0xf9, 0x06, 0xe0, 0xee, 0xb4, 0x23, 0x4f, 0x7a, 0xe6, 0x89, 0xd3, 0x2b, 0x9e, 0x38,
	0xbd, 0xb7, 0xfa, 0xfd, 0xd3, 0x79, 0x62, 0x2f, 0xe8, 0x2b, 0xa7, 0x62, 0xf7, 0x01, 0xf1, 0x61,
	0x6f, 0xed, 0xae, 0x42, 0x9e, 0x2d, 0xdd, 0xe7, 0x57, 0xae, 0x12, 0x9d, 0xc3, 0x7b, 0xb4, 0xa5,
	0xcf, 0x6b, 0x3c, 0x81, 0x57, 0x0e, 0x7e, 0x52, 0x0c, 0xdb, 0x7c, 0x41, 0xe9, 0x3c, 0xbf, 0x4f,
	0x5d, 0xba, 0xfd, 0x16, 0x76, 0x57, 0xaf, 0xad, 0xe4, 0xa9, 0x1d, 0xb5, 0xe9, 0x3e, 0xdc, 0x79,
	0xb6, 0x59, 0x59, 0x3a, 0x7c, 0x07, 0xad, 0xa5, 0xcb, 0x27, 0xf1, 0x16, 0x07, 0x2c, 0xde, 0x67,
	0x3b, 0x07, 0x1b, 0x34, 0xa5, 0x9f, 0x0b, 0x68, 0x2e, 0xdc, 0xf0, 0x09, 0x06, 0x7b, 0xfd, 0xca,
	0xdf, 0x79, 0xae, 0xab, 0xad, 0x5c, 0x1e, 0xaa, 0xb4, 0xd5, 0x5a, 0xe0, 0x56, 0x5e, 0x24, 0xe4,
	0xf0, 0xbf, 0xbe, 0xae, 0xca, 0xc0, 0xdd, 0xf3, 0x90, 0xe9, 0x3e, 0x20, 0x21, 0x78, 0xf7, 0xbd,
	0x5c, 0x7f, 0xc8, 0xf9, 0xcf, 0xb4, 0xfa, 0x87, 0x9e, 0xbd, 0xdd, 0x07, 0xbf, 0x74, 0xde, 0xfc,
	0xea, 0x0f, 0x27, 0xc3, 0x58, 0x8d, 0xb2, 0x1b, 0xbd, 0x15, 0xfb, 0x37, 0x52, 0x84, 0x94, 0xca,
	0x7e, 0x38, 0x8a, 0x65, 0x92, 0x2a, 0x1a, 0xde, 0x7e, 0x49, 0x93, 0xb8, 0x3f, 0x14, 0xfd, 0xe9,
	0x57, 0xfd, 0xbb, 0xd7, 0xfd, 0xcd, 0x36, 0x16, 0xea, 0x57, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x65, 0x52, 0x22, 0x42, 0xf2, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HandyRustyServiceClient is the client API for HandyRustyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HandyRustyServiceClient interface {
	// GetVersion returns the ChirpStack Network Server version.
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// GetDeviceCounters returns the summary-counters log-items for given organisation_id
	GetDeviceCounters(ctx context.Context, in *GetDeviceCountersRequest, opts ...grpc.CallOption) (*GetDeviceCountersResponse, error)
	// GetDeviceCounters returns the summary-counters log-items for given organisation_id
	GetGatewayCounters(ctx context.Context, in *GetGatewayCountersRequest, opts ...grpc.CallOption) (*GetGatewayCountersResponse, error)
	// GetFrameCounters returns the summary-counters of frames by type
	GetFrameCounters(ctx context.Context, in *GetFrameCountersRequest, opts ...grpc.CallOption) (*GetFrameCountersResponse, error)
	// GetFramesSpeed returns the frames per minute array for given timedate gap
	GetFrameSpeed(ctx context.Context, in *GetFrameSpeedRequest, opts ...grpc.CallOption) (*GetFrameSpeedResponse, error)
	// ExecCommand sends command to the gateway and returns the answer
	ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (*gw.GatewayCommandExecResponse, error)
	// GetDeviceFramesLog returns an array with device-frame logs
	GetDeviceFramesLog(ctx context.Context, in *GetDeviceFramesLogRequest, opts ...grpc.CallOption) (*GetDeviceFramesLogResponse, error)
	// StreamDeviceFramesLogCSV streams the frame-logs from handyrusty CH-storage.
	StreamDeviceFramesLogCSV(ctx context.Context, in *GetDeviceFramesLogRequest, opts ...grpc.CallOption) (HandyRustyService_StreamDeviceFramesLogCSVClient, error)
}

type handyRustyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandyRustyServiceClient(cc grpc.ClientConnInterface) HandyRustyServiceClient {
	return &handyRustyServiceClient{cc}
}

func (c *handyRustyServiceClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) GetDeviceCounters(ctx context.Context, in *GetDeviceCountersRequest, opts ...grpc.CallOption) (*GetDeviceCountersResponse, error) {
	out := new(GetDeviceCountersResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/GetDeviceCounters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) GetGatewayCounters(ctx context.Context, in *GetGatewayCountersRequest, opts ...grpc.CallOption) (*GetGatewayCountersResponse, error) {
	out := new(GetGatewayCountersResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/GetGatewayCounters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) GetFrameCounters(ctx context.Context, in *GetFrameCountersRequest, opts ...grpc.CallOption) (*GetFrameCountersResponse, error) {
	out := new(GetFrameCountersResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/GetFrameCounters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) GetFrameSpeed(ctx context.Context, in *GetFrameSpeedRequest, opts ...grpc.CallOption) (*GetFrameSpeedResponse, error) {
	out := new(GetFrameSpeedResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/GetFrameSpeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (*gw.GatewayCommandExecResponse, error) {
	out := new(gw.GatewayCommandExecResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/ExecCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) GetDeviceFramesLog(ctx context.Context, in *GetDeviceFramesLogRequest, opts ...grpc.CallOption) (*GetDeviceFramesLogResponse, error) {
	out := new(GetDeviceFramesLogResponse)
	err := c.cc.Invoke(ctx, "/hr.HandyRustyService/GetDeviceFramesLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handyRustyServiceClient) StreamDeviceFramesLogCSV(ctx context.Context, in *GetDeviceFramesLogRequest, opts ...grpc.CallOption) (HandyRustyService_StreamDeviceFramesLogCSVClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HandyRustyService_serviceDesc.Streams[0], "/hr.HandyRustyService/StreamDeviceFramesLogCSV", opts...)
	if err != nil {
		return nil, err
	}
	x := &handyRustyServiceStreamDeviceFramesLogCSVClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HandyRustyService_StreamDeviceFramesLogCSVClient interface {
	Recv() (*StreamDeviceFramesLogCSVResponse, error)
	grpc.ClientStream
}

type handyRustyServiceStreamDeviceFramesLogCSVClient struct {
	grpc.ClientStream
}

func (x *handyRustyServiceStreamDeviceFramesLogCSVClient) Recv() (*StreamDeviceFramesLogCSVResponse, error) {
	m := new(StreamDeviceFramesLogCSVResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HandyRustyServiceServer is the server API for HandyRustyService service.
type HandyRustyServiceServer interface {
	// GetVersion returns the ChirpStack Network Server version.
	GetVersion(context.Context, *empty.Empty) (*GetVersionResponse, error)
	// GetDeviceCounters returns the summary-counters log-items for given organisation_id
	GetDeviceCounters(context.Context, *GetDeviceCountersRequest) (*GetDeviceCountersResponse, error)
	// GetDeviceCounters returns the summary-counters log-items for given organisation_id
	GetGatewayCounters(context.Context, *GetGatewayCountersRequest) (*GetGatewayCountersResponse, error)
	// GetFrameCounters returns the summary-counters of frames by type
	GetFrameCounters(context.Context, *GetFrameCountersRequest) (*GetFrameCountersResponse, error)
	// GetFramesSpeed returns the frames per minute array for given timedate gap
	GetFrameSpeed(context.Context, *GetFrameSpeedRequest) (*GetFrameSpeedResponse, error)
	// ExecCommand sends command to the gateway and returns the answer
	ExecCommand(context.Context, *ExecCommandRequest) (*gw.GatewayCommandExecResponse, error)
	// GetDeviceFramesLog returns an array with device-frame logs
	GetDeviceFramesLog(context.Context, *GetDeviceFramesLogRequest) (*GetDeviceFramesLogResponse, error)
	// StreamDeviceFramesLogCSV streams the frame-logs from handyrusty CH-storage.
	StreamDeviceFramesLogCSV(*GetDeviceFramesLogRequest, HandyRustyService_StreamDeviceFramesLogCSVServer) error
}

// UnimplementedHandyRustyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHandyRustyServiceServer struct {
}

func (*UnimplementedHandyRustyServiceServer) GetVersion(ctx context.Context, req *empty.Empty) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (*UnimplementedHandyRustyServiceServer) GetDeviceCounters(ctx context.Context, req *GetDeviceCountersRequest) (*GetDeviceCountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceCounters not implemented")
}
func (*UnimplementedHandyRustyServiceServer) GetGatewayCounters(ctx context.Context, req *GetGatewayCountersRequest) (*GetGatewayCountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayCounters not implemented")
}
func (*UnimplementedHandyRustyServiceServer) GetFrameCounters(ctx context.Context, req *GetFrameCountersRequest) (*GetFrameCountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrameCounters not implemented")
}
func (*UnimplementedHandyRustyServiceServer) GetFrameSpeed(ctx context.Context, req *GetFrameSpeedRequest) (*GetFrameSpeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrameSpeed not implemented")
}
func (*UnimplementedHandyRustyServiceServer) ExecCommand(ctx context.Context, req *ExecCommandRequest) (*gw.GatewayCommandExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}
func (*UnimplementedHandyRustyServiceServer) GetDeviceFramesLog(ctx context.Context, req *GetDeviceFramesLogRequest) (*GetDeviceFramesLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceFramesLog not implemented")
}
func (*UnimplementedHandyRustyServiceServer) StreamDeviceFramesLogCSV(req *GetDeviceFramesLogRequest, srv HandyRustyService_StreamDeviceFramesLogCSVServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDeviceFramesLogCSV not implemented")
}

func RegisterHandyRustyServiceServer(s *grpc.Server, srv HandyRustyServiceServer) {
	s.RegisterService(&_HandyRustyService_serviceDesc, srv)
}

func _HandyRustyService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_GetDeviceCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).GetDeviceCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/GetDeviceCounters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).GetDeviceCounters(ctx, req.(*GetDeviceCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_GetGatewayCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).GetGatewayCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/GetGatewayCounters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).GetGatewayCounters(ctx, req.(*GetGatewayCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_GetFrameCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).GetFrameCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/GetFrameCounters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).GetFrameCounters(ctx, req.(*GetFrameCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_GetFrameSpeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameSpeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).GetFrameSpeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/GetFrameSpeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).GetFrameSpeed(ctx, req.(*GetFrameSpeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/ExecCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).ExecCommand(ctx, req.(*ExecCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_GetDeviceFramesLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceFramesLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandyRustyServiceServer).GetDeviceFramesLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hr.HandyRustyService/GetDeviceFramesLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandyRustyServiceServer).GetDeviceFramesLog(ctx, req.(*GetDeviceFramesLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandyRustyService_StreamDeviceFramesLogCSV_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDeviceFramesLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HandyRustyServiceServer).StreamDeviceFramesLogCSV(m, &handyRustyServiceStreamDeviceFramesLogCSVServer{stream})
}

type HandyRustyService_StreamDeviceFramesLogCSVServer interface {
	Send(*StreamDeviceFramesLogCSVResponse) error
	grpc.ServerStream
}

type handyRustyServiceStreamDeviceFramesLogCSVServer struct {
	grpc.ServerStream
}

func (x *handyRustyServiceStreamDeviceFramesLogCSVServer) Send(m *StreamDeviceFramesLogCSVResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _HandyRustyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hr.HandyRustyService",
	HandlerType: (*HandyRustyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _HandyRustyService_GetVersion_Handler,
		},
		{
			MethodName: "GetDeviceCounters",
			Handler:    _HandyRustyService_GetDeviceCounters_Handler,
		},
		{
			MethodName: "GetGatewayCounters",
			Handler:    _HandyRustyService_GetGatewayCounters_Handler,
		},
		{
			MethodName: "GetFrameCounters",
			Handler:    _HandyRustyService_GetFrameCounters_Handler,
		},
		{
			MethodName: "GetFrameSpeed",
			Handler:    _HandyRustyService_GetFrameSpeed_Handler,
		},
		{
			MethodName: "ExecCommand",
			Handler:    _HandyRustyService_ExecCommand_Handler,
		},
		{
			MethodName: "GetDeviceFramesLog",
			Handler:    _HandyRustyService_GetDeviceFramesLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDeviceFramesLogCSV",
			Handler:       _HandyRustyService_StreamDeviceFramesLogCSV_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "handyrusty/hr.proto",
}
