# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chirpstack_api.gw import gw_pb2 as chirpstack__api_dot_gw_dot_gw__pb2
from chirpstack_api.handyrusty import hr_pb2 as chirpstack__api_dot_handyrusty_dot_hr__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chirpstack_api/handyrusty/hr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HandyRustyServiceStub(object):
    """HandyRustyService provides the "handy-rusty additional enforta tools" API methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/hr.HandyRustyService/GetVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.GetDeviceCounters = channel.unary_unary(
                '/hr.HandyRustyService/GetDeviceCounters',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceCountersRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceCountersResponse.FromString,
                _registered_method=True)
        self.GetGatewayCounters = channel.unary_unary(
                '/hr.HandyRustyService/GetGatewayCounters',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGatewayCountersRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGatewayCountersResponse.FromString,
                _registered_method=True)
        self.GetFrameCounters = channel.unary_unary(
                '/hr.HandyRustyService/GetFrameCounters',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameCountersRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameCountersResponse.FromString,
                _registered_method=True)
        self.GetFrameSpeed = channel.unary_unary(
                '/hr.HandyRustyService/GetFrameSpeed',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameSpeedRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameSpeedResponse.FromString,
                _registered_method=True)
        self.ExecCommand = channel.unary_unary(
                '/hr.HandyRustyService/ExecCommand',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.ExecCommandRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_gw_dot_gw__pb2.GatewayCommandExecResponse.FromString,
                _registered_method=True)
        self.GetDeviceFrames = channel.unary_unary(
                '/hr.HandyRustyService/GetDeviceFrames',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesResponse.FromString,
                _registered_method=True)
        self.StreamDeviceFramesCSV = channel.unary_stream(
                '/hr.HandyRustyService/StreamDeviceFramesCSV',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.StreamDeviceFramesCSVResponse.FromString,
                _registered_method=True)
        self.GetCurrentState = channel.unary_unary(
                '/hr.HandyRustyService/GetCurrentState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetCurrentStateResponse.FromString,
                _registered_method=True)
        self.StoreIntegrationReplies = channel.unary_unary(
                '/hr.HandyRustyService/StoreIntegrationReplies',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.StoreIntegrationReplyRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.StoreIntegrationReplyResponse.FromString,
                _registered_method=True)
        self.GetIntegrationReplies = channel.unary_unary(
                '/hr.HandyRustyService/GetIntegrationReplies',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetIntegrationRepliesRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetIntegrationRepliesResponse.FromString,
                _registered_method=True)
        self.GetGatewayLogs = channel.unary_unary(
                '/hr.HandyRustyService/GetGatewayLogs',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.LogsGatewayRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.LogsGatewayResponse.FromString,
                _registered_method=True)
        self.GetGwStats = channel.unary_unary(
                '/hr.HandyRustyService/GetGwStats',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGwStatsRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGwStatsResponse.FromString,
                _registered_method=True)
        self.GetDeviceStats = channel.unary_unary(
                '/hr.HandyRustyService/GetDeviceStats',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatsLastTwoweeks = channel.unary_unary(
                '/hr.HandyRustyService/GetDeviceStatsLastTwoweeks',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsLastTwoweeksResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatsLastTwoweeksAggregated = channel.unary_unary(
                '/hr.HandyRustyService/GetDeviceStatsLastTwoweeksAggregated',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsLastTwoweeksResponse.FromString,
                _registered_method=True)
        self.GetAveragesForDeviceList = channel.unary_unary(
                '/hr.HandyRustyService/GetAveragesForDeviceList',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetAveragesForDeviceListRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetAveragesForDeviceListResponse.FromString,
                _registered_method=True)
        self.CountDeviceFramesPerDevEui = channel.unary_unary(
                '/hr.HandyRustyService/CountDeviceFramesPerDevEui',
                request_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.CountDeviceFramesPerDevEuiRequest.SerializeToString,
                response_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.CountDeviceFramesPerDevEuiResponse.FromString,
                _registered_method=True)


class HandyRustyServiceServicer(object):
    """HandyRustyService provides the "handy-rusty additional enforta tools" API methods.
    """

    def GetVersion(self, request, context):
        """GetVersion returns the ChirpStack Network Server version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceCounters(self, request, context):
        """GetDeviceCounters returns the summary-counters log-items for given organisation_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGatewayCounters(self, request, context):
        """GetDeviceCounters returns the summary-counters log-items for given organisation_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFrameCounters(self, request, context):
        """GetFrameCounters returns the summary-counters of frames by type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFrameSpeed(self, request, context):
        """GetFramesSpeed returns the frames per minute array for given timedate gap
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecCommand(self, request, context):
        """ExecCommand sends command to the gateway and returns the answer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceFrames(self, request, context):
        """GetDeviceFrames returns an array with device-frame logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDeviceFramesCSV(self, request, context):
        """StreamDeviceFramesCSV streams the frame-logs from handyrusty CH-storage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentState(self, request, context):
        """GetCurrentState returns items for monitoring purposes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreIntegrationReplies(self, request, context):
        """Store to clickhouse replies of integration event notifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrationReplies(self, request, context):
        """Get replies of integration event notifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGatewayLogs(self, request, context):
        """Get dictionaries from clickhouse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGwStats(self, request, context):
        """Get stats for gateway from clickhouse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStats(self, request, context):
        """Get stats for device from clickhouse current
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatsLastTwoweeks(self, request, context):
        """Get stats for device from clickhouse for last 14 days
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatsLastTwoweeksAggregated(self, request, context):
        """Get stats for device from clickhouse for last 14 days aggregated by day
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAveragesForDeviceList(self, request, context):
        """Get stats for device from clickhouse for last 14 days aggregated by day
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDeviceFramesPerDevEui(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandyRustyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetVersionResponse.SerializeToString,
            ),
            'GetDeviceCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceCounters,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceCountersRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceCountersResponse.SerializeToString,
            ),
            'GetGatewayCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGatewayCounters,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGatewayCountersRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGatewayCountersResponse.SerializeToString,
            ),
            'GetFrameCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrameCounters,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameCountersRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameCountersResponse.SerializeToString,
            ),
            'GetFrameSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrameSpeed,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameSpeedRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameSpeedResponse.SerializeToString,
            ),
            'ExecCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecCommand,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.ExecCommandRequest.FromString,
                    response_serializer=chirpstack__api_dot_gw_dot_gw__pb2.GatewayCommandExecResponse.SerializeToString,
            ),
            'GetDeviceFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceFrames,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesResponse.SerializeToString,
            ),
            'StreamDeviceFramesCSV': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDeviceFramesCSV,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.StreamDeviceFramesCSVResponse.SerializeToString,
            ),
            'GetCurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetCurrentStateResponse.SerializeToString,
            ),
            'StoreIntegrationReplies': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreIntegrationReplies,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.StoreIntegrationReplyRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.StoreIntegrationReplyResponse.SerializeToString,
            ),
            'GetIntegrationReplies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrationReplies,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetIntegrationRepliesRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetIntegrationRepliesResponse.SerializeToString,
            ),
            'GetGatewayLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGatewayLogs,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.LogsGatewayRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.LogsGatewayResponse.SerializeToString,
            ),
            'GetGwStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGwStats,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGwStatsRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGwStatsResponse.SerializeToString,
            ),
            'GetDeviceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStats,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsResponse.SerializeToString,
            ),
            'GetDeviceStatsLastTwoweeks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatsLastTwoweeks,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsLastTwoweeksResponse.SerializeToString,
            ),
            'GetDeviceStatsLastTwoweeksAggregated': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatsLastTwoweeksAggregated,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsLastTwoweeksResponse.SerializeToString,
            ),
            'GetAveragesForDeviceList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAveragesForDeviceList,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetAveragesForDeviceListRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.GetAveragesForDeviceListResponse.SerializeToString,
            ),
            'CountDeviceFramesPerDevEui': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDeviceFramesPerDevEui,
                    request_deserializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.CountDeviceFramesPerDevEuiRequest.FromString,
                    response_serializer=chirpstack__api_dot_handyrusty_dot_hr__pb2.CountDeviceFramesPerDevEuiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hr.HandyRustyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hr.HandyRustyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HandyRustyService(object):
    """HandyRustyService provides the "handy-rusty additional enforta tools" API methods.
    """

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetDeviceCounters',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceCountersRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceCountersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGatewayCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetGatewayCounters',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGatewayCountersRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGatewayCountersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFrameCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetFrameCounters',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameCountersRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameCountersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFrameSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetFrameSpeed',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameSpeedRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetFrameSpeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/ExecCommand',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.ExecCommandRequest.SerializeToString,
            chirpstack__api_dot_gw_dot_gw__pb2.GatewayCommandExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetDeviceFrames',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDeviceFramesCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hr.HandyRustyService/StreamDeviceFramesCSV',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceFramesRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.StreamDeviceFramesCSVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetCurrentState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetCurrentStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreIntegrationReplies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/StoreIntegrationReplies',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.StoreIntegrationReplyRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.StoreIntegrationReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegrationReplies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetIntegrationReplies',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetIntegrationRepliesRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetIntegrationRepliesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGatewayLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetGatewayLogs',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.LogsGatewayRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.LogsGatewayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGwStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetGwStats',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGwStatsRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetGwStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetDeviceStats',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatsLastTwoweeks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetDeviceStatsLastTwoweeks',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsLastTwoweeksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatsLastTwoweeksAggregated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetDeviceStatsLastTwoweeksAggregated',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetDeviceStatsLastTwoweeksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAveragesForDeviceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/GetAveragesForDeviceList',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetAveragesForDeviceListRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.GetAveragesForDeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDeviceFramesPerDevEui(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hr.HandyRustyService/CountDeviceFramesPerDevEui',
            chirpstack__api_dot_handyrusty_dot_hr__pb2.CountDeviceFramesPerDevEuiRequest.SerializeToString,
            chirpstack__api_dot_handyrusty_dot_hr__pb2.CountDeviceFramesPerDevEuiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
